/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const d: typeof import('./src/utils/debug').d
  const dt: typeof import('./src/utils/debug').dt
  const timePromise: typeof import('./src/utils/debug').timePromise
}
