rename-window 'dev-and-test'
send-keys 'just dev' C-m
# split-window -h 'bun run test'
new-window -n 'web'
send-keys 'cd apps/web/rllm' C-m
new-window -n 'omp'
send-keys 'cd ../agent && jj workspace update-stale && omp' C-m
