// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peers/v1/broadcast.proto

package peers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Publish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_peers_v1_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_peers_v1_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *Publish) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Publish) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Publish) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_peers_v1_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_peers_v1_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *Subscribe) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type BroadcastMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*BroadcastMessage_Publish
	//	*BroadcastMessage_Subscribe
	Message       isBroadcastMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_peers_v1_broadcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_broadcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_peers_v1_broadcast_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastMessage) GetMessage() isBroadcastMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BroadcastMessage) GetPublish() *Publish {
	if x != nil {
		if x, ok := x.Message.(*BroadcastMessage_Publish); ok {
			return x.Publish
		}
	}
	return nil
}

func (x *BroadcastMessage) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Message.(*BroadcastMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

type isBroadcastMessage_Message interface {
	isBroadcastMessage_Message()
}

type BroadcastMessage_Publish struct {
	Publish *Publish `protobuf:"bytes,1,opt,name=publish,proto3,oneof"`
}

type BroadcastMessage_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

func (*BroadcastMessage_Publish) isBroadcastMessage_Message() {}

func (*BroadcastMessage_Subscribe) isBroadcastMessage_Message() {}

var File_peers_v1_broadcast_proto protoreflect.FileDescriptor

const file_peers_v1_broadcast_proto_rawDesc = "" +
	"\n" +
	"\x18peers/v1/broadcast.proto\x12\bpeers.v1\"Q\n" +
	"\aPublish\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"!\n" +
	"\tSubscribe\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x81\x01\n" +
	"\x10BroadcastMessage\x12-\n" +
	"\apublish\x18\x01 \x01(\v2\x11.peers.v1.PublishH\x00R\apublish\x123\n" +
	"\tsubscribe\x18\x02 \x01(\v2\x13.peers.v1.SubscribeH\x00R\tsubscribeB\t\n" +
	"\amessageB\rZ\vproto/peersb\x06proto3"

var (
	file_peers_v1_broadcast_proto_rawDescOnce sync.Once
	file_peers_v1_broadcast_proto_rawDescData []byte
)

func file_peers_v1_broadcast_proto_rawDescGZIP() []byte {
	file_peers_v1_broadcast_proto_rawDescOnce.Do(func() {
		file_peers_v1_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peers_v1_broadcast_proto_rawDesc), len(file_peers_v1_broadcast_proto_rawDesc)))
	})
	return file_peers_v1_broadcast_proto_rawDescData
}

var file_peers_v1_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_peers_v1_broadcast_proto_goTypes = []any{
	(*Publish)(nil),          // 0: peers.v1.Publish
	(*Subscribe)(nil),        // 1: peers.v1.Subscribe
	(*BroadcastMessage)(nil), // 2: peers.v1.BroadcastMessage
}
var file_peers_v1_broadcast_proto_depIdxs = []int32{
	0, // 0: peers.v1.BroadcastMessage.publish:type_name -> peers.v1.Publish
	1, // 1: peers.v1.BroadcastMessage.subscribe:type_name -> peers.v1.Subscribe
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_peers_v1_broadcast_proto_init() }
func file_peers_v1_broadcast_proto_init() {
	if File_peers_v1_broadcast_proto != nil {
		return
	}
	file_peers_v1_broadcast_proto_msgTypes[2].OneofWrappers = []any{
		(*BroadcastMessage_Publish)(nil),
		(*BroadcastMessage_Subscribe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peers_v1_broadcast_proto_rawDesc), len(file_peers_v1_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peers_v1_broadcast_proto_goTypes,
		DependencyIndexes: file_peers_v1_broadcast_proto_depIdxs,
		MessageInfos:      file_peers_v1_broadcast_proto_msgTypes,
	}.Build()
	File_peers_v1_broadcast_proto = out.File
	file_peers_v1_broadcast_proto_goTypes = nil
	file_peers_v1_broadcast_proto_depIdxs = nil
}
