// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peers/v1/peer.proto

package peers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RootDigest    []byte                 `protobuf:"bytes,3,opt,name=root_digest,json=rootDigest,proto3,oneof" json:"root_digest,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHandshake) Reset() {
	*x = SyncHandshake{}
	mi := &file_peers_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHandshake) ProtoMessage() {}

func (x *SyncHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHandshake.ProtoReflect.Descriptor instead.
func (*SyncHandshake) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *SyncHandshake) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SyncHandshake) GetRootDigest() []byte {
	if x != nil {
		return x.RootDigest
	}
	return nil
}

func (x *SyncHandshake) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DigestQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []uint32               `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestQuery) Reset() {
	*x = DigestQuery{}
	mi := &file_peers_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestQuery) ProtoMessage() {}

func (x *DigestQuery) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestQuery.ProtoReflect.Descriptor instead.
func (*DigestQuery) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *DigestQuery) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

type DigestQueries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleDepth   uint32                 `protobuf:"varint,1,opt,name=merkle_depth,json=merkleDepth,proto3" json:"merkle_depth,omitempty"`
	Queries       []*DigestQuery         `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestQueries) Reset() {
	*x = DigestQueries{}
	mi := &file_peers_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestQueries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestQueries) ProtoMessage() {}

func (x *DigestQueries) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestQueries.ProtoReflect.Descriptor instead.
func (*DigestQueries) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *DigestQueries) GetMerkleDepth() uint32 {
	if x != nil {
		return x.MerkleDepth
	}
	return 0
}

func (x *DigestQueries) GetQueries() []*DigestQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type DigestUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []uint32               `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestUpdate) Reset() {
	*x = DigestUpdate{}
	mi := &file_peers_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestUpdate) ProtoMessage() {}

func (x *DigestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestUpdate.ProtoReflect.Descriptor instead.
func (*DigestUpdate) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{3}
}

func (x *DigestUpdate) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *DigestUpdate) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *DigestUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type DigestUpdates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleDepth   uint32                 `protobuf:"varint,1,opt,name=merkle_depth,json=merkleDepth,proto3" json:"merkle_depth,omitempty"`
	Updates       []*DigestUpdate        `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestUpdates) Reset() {
	*x = DigestUpdates{}
	mi := &file_peers_v1_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestUpdates) ProtoMessage() {}

func (x *DigestUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestUpdates.ProtoReflect.Descriptor instead.
func (*DigestUpdates) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{4}
}

func (x *DigestUpdates) GetMerkleDepth() uint32 {
	if x != nil {
		return x.MerkleDepth
	}
	return 0
}

func (x *DigestUpdates) GetUpdates() []*DigestUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type EventBatchPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatchPayload) Reset() {
	*x = EventBatchPayload{}
	mi := &file_peers_v1_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatchPayload) ProtoMessage() {}

func (x *EventBatchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatchPayload.ProtoReflect.Descriptor instead.
func (*EventBatchPayload) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{5}
}

func (x *EventBatchPayload) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EventBatchPayload) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EventBatchPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendEventsWithTimestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamps    []string               `protobuf:"bytes,1,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventsWithTimestamps) Reset() {
	*x = SendEventsWithTimestamps{}
	mi := &file_peers_v1_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventsWithTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventsWithTimestamps) ProtoMessage() {}

func (x *SendEventsWithTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventsWithTimestamps.ProtoReflect.Descriptor instead.
func (*SendEventsWithTimestamps) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{6}
}

func (x *SendEventsWithTimestamps) GetTimestamps() []string {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventBatchPayload   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_peers_v1_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{7}
}

func (x *EventBatch) GetEvents() []*EventBatchPayload {
	if x != nil {
		return x.Events
	}
	return nil
}

type SyncWireMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ClientId  string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncWireMessage_Handshake
	//	*SyncWireMessage_DigestQueries
	//	*SyncWireMessage_DigestUpdates
	//	*SyncWireMessage_EventBatch
	//	*SyncWireMessage_SendEventsWithTimestamps
	Payload       isSyncWireMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWireMessage) Reset() {
	*x = SyncWireMessage{}
	mi := &file_peers_v1_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWireMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWireMessage) ProtoMessage() {}

func (x *SyncWireMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWireMessage.ProtoReflect.Descriptor instead.
func (*SyncWireMessage) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{8}
}

func (x *SyncWireMessage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SyncWireMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SyncWireMessage) GetPayload() isSyncWireMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncWireMessage) GetHandshake() *SyncHandshake {
	if x != nil {
		if x, ok := x.Payload.(*SyncWireMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *SyncWireMessage) GetDigestQueries() *DigestQueries {
	if x != nil {
		if x, ok := x.Payload.(*SyncWireMessage_DigestQueries); ok {
			return x.DigestQueries
		}
	}
	return nil
}

func (x *SyncWireMessage) GetDigestUpdates() *DigestUpdates {
	if x != nil {
		if x, ok := x.Payload.(*SyncWireMessage_DigestUpdates); ok {
			return x.DigestUpdates
		}
	}
	return nil
}

func (x *SyncWireMessage) GetEventBatch() *EventBatch {
	if x != nil {
		if x, ok := x.Payload.(*SyncWireMessage_EventBatch); ok {
			return x.EventBatch
		}
	}
	return nil
}

func (x *SyncWireMessage) GetSendEventsWithTimestamps() *SendEventsWithTimestamps {
	if x != nil {
		if x, ok := x.Payload.(*SyncWireMessage_SendEventsWithTimestamps); ok {
			return x.SendEventsWithTimestamps
		}
	}
	return nil
}

type isSyncWireMessage_Payload interface {
	isSyncWireMessage_Payload()
}

type SyncWireMessage_Handshake struct {
	Handshake *SyncHandshake `protobuf:"bytes,3,opt,name=handshake,proto3,oneof"`
}

type SyncWireMessage_DigestQueries struct {
	DigestQueries *DigestQueries `protobuf:"bytes,4,opt,name=digest_queries,json=digestQueries,proto3,oneof"`
}

type SyncWireMessage_DigestUpdates struct {
	DigestUpdates *DigestUpdates `protobuf:"bytes,5,opt,name=digest_updates,json=digestUpdates,proto3,oneof"`
}

type SyncWireMessage_EventBatch struct {
	EventBatch *EventBatch `protobuf:"bytes,6,opt,name=event_batch,json=eventBatch,proto3,oneof"`
}

type SyncWireMessage_SendEventsWithTimestamps struct {
	SendEventsWithTimestamps *SendEventsWithTimestamps `protobuf:"bytes,7,opt,name=send_events_with_timestamps,json=sendEventsWithTimestamps,proto3,oneof"`
}

func (*SyncWireMessage_Handshake) isSyncWireMessage_Payload() {}

func (*SyncWireMessage_DigestQueries) isSyncWireMessage_Payload() {}

func (*SyncWireMessage_DigestUpdates) isSyncWireMessage_Payload() {}

func (*SyncWireMessage_EventBatch) isSyncWireMessage_Payload() {}

func (*SyncWireMessage_SendEventsWithTimestamps) isSyncWireMessage_Payload() {}

var File_peers_v1_peer_proto protoreflect.FileDescriptor

const file_peers_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x13peers/v1/peer.proto\x12\bpeers.v1\"|\n" +
	"\rSyncHandshake\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12$\n" +
	"\vroot_digest\x18\x03 \x01(\fH\x00R\n" +
	"rootDigest\x88\x01\x01\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientIdB\x0e\n" +
	"\f_root_digest\"!\n" +
	"\vDigestQuery\x12\x12\n" +
	"\x04path\x18\x01 \x03(\rR\x04path\"c\n" +
	"\rDigestQueries\x12!\n" +
	"\fmerkle_depth\x18\x01 \x01(\rR\vmerkleDepth\x12/\n" +
	"\aqueries\x18\x02 \x03(\v2\x15.peers.v1.DigestQueryR\aqueries\"X\n" +
	"\fDigestUpdate\x12\x12\n" +
	"\x04path\x18\x01 \x03(\rR\x04path\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"d\n" +
	"\rDigestUpdates\x12!\n" +
	"\fmerkle_depth\x18\x01 \x01(\rR\vmerkleDepth\x120\n" +
	"\aupdates\x18\x02 \x03(\v2\x16.peers.v1.DigestUpdateR\aupdates\"c\n" +
	"\x11EventBatchPayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\":\n" +
	"\x18SendEventsWithTimestamps\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x01 \x03(\tR\n" +
	"timestamps\"A\n" +
	"\n" +
	"EventBatch\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.peers.v1.EventBatchPayloadR\x06events\"\xb3\x03\n" +
	"\x0fSyncWireMessage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x127\n" +
	"\thandshake\x18\x03 \x01(\v2\x17.peers.v1.SyncHandshakeH\x00R\thandshake\x12@\n" +
	"\x0edigest_queries\x18\x04 \x01(\v2\x17.peers.v1.DigestQueriesH\x00R\rdigestQueries\x12@\n" +
	"\x0edigest_updates\x18\x05 \x01(\v2\x17.peers.v1.DigestUpdatesH\x00R\rdigestUpdates\x127\n" +
	"\vevent_batch\x18\x06 \x01(\v2\x14.peers.v1.EventBatchH\x00R\n" +
	"eventBatch\x12c\n" +
	"\x1bsend_events_with_timestamps\x18\a \x01(\v2\".peers.v1.SendEventsWithTimestampsH\x00R\x18sendEventsWithTimestampsB\t\n" +
	"\apayloadB\rZ\vproto/peersb\x06proto3"

var (
	file_peers_v1_peer_proto_rawDescOnce sync.Once
	file_peers_v1_peer_proto_rawDescData []byte
)

func file_peers_v1_peer_proto_rawDescGZIP() []byte {
	file_peers_v1_peer_proto_rawDescOnce.Do(func() {
		file_peers_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peers_v1_peer_proto_rawDesc), len(file_peers_v1_peer_proto_rawDesc)))
	})
	return file_peers_v1_peer_proto_rawDescData
}

var file_peers_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_peers_v1_peer_proto_goTypes = []any{
	(*SyncHandshake)(nil),            // 0: peers.v1.SyncHandshake
	(*DigestQuery)(nil),              // 1: peers.v1.DigestQuery
	(*DigestQueries)(nil),            // 2: peers.v1.DigestQueries
	(*DigestUpdate)(nil),             // 3: peers.v1.DigestUpdate
	(*DigestUpdates)(nil),            // 4: peers.v1.DigestUpdates
	(*EventBatchPayload)(nil),        // 5: peers.v1.EventBatchPayload
	(*SendEventsWithTimestamps)(nil), // 6: peers.v1.SendEventsWithTimestamps
	(*EventBatch)(nil),               // 7: peers.v1.EventBatch
	(*SyncWireMessage)(nil),          // 8: peers.v1.SyncWireMessage
}
var file_peers_v1_peer_proto_depIdxs = []int32{
	1, // 0: peers.v1.DigestQueries.queries:type_name -> peers.v1.DigestQuery
	3, // 1: peers.v1.DigestUpdates.updates:type_name -> peers.v1.DigestUpdate
	5, // 2: peers.v1.EventBatch.events:type_name -> peers.v1.EventBatchPayload
	0, // 3: peers.v1.SyncWireMessage.handshake:type_name -> peers.v1.SyncHandshake
	2, // 4: peers.v1.SyncWireMessage.digest_queries:type_name -> peers.v1.DigestQueries
	4, // 5: peers.v1.SyncWireMessage.digest_updates:type_name -> peers.v1.DigestUpdates
	7, // 6: peers.v1.SyncWireMessage.event_batch:type_name -> peers.v1.EventBatch
	6, // 7: peers.v1.SyncWireMessage.send_events_with_timestamps:type_name -> peers.v1.SendEventsWithTimestamps
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_peers_v1_peer_proto_init() }
func file_peers_v1_peer_proto_init() {
	if File_peers_v1_peer_proto != nil {
		return
	}
	file_peers_v1_peer_proto_msgTypes[0].OneofWrappers = []any{}
	file_peers_v1_peer_proto_msgTypes[8].OneofWrappers = []any{
		(*SyncWireMessage_Handshake)(nil),
		(*SyncWireMessage_DigestQueries)(nil),
		(*SyncWireMessage_DigestUpdates)(nil),
		(*SyncWireMessage_EventBatch)(nil),
		(*SyncWireMessage_SendEventsWithTimestamps)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peers_v1_peer_proto_rawDesc), len(file_peers_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peers_v1_peer_proto_goTypes,
		DependencyIndexes: file_peers_v1_peer_proto_depIdxs,
		MessageInfos:      file_peers_v1_peer_proto_msgTypes,
	}.Build()
	File_peers_v1_peer_proto = out.File
	file_peers_v1_peer_proto_goTypes = nil
	file_peers_v1_peer_proto_depIdxs = nil
}
