FROM golang:bookworm AS builder
WORKDIR /app
COPY . .
RUN go mod download;
RUN --mount=type=cache,id=s/9198bc32-97e7-4be3-944b-cb5f323ddbb4-/go/pkgs/mod,target=/go/pkg/mod \
    --mount=type=cache,id=s/9198bc32-97e7-4be3-944b-cb5f323ddbb4-/root/.cache/go-build,target=/root/.cache/go-build \
    cd apps/sync-server-go && \
    CGO_ENABLED=0 GOOS=linux go build \
      -ldflags="-w -s" \
      -o /app/server .

FROM debian:bookworm-slim
RUN --mount=type=cache,id=s/9198bc32-97e7-4be3-944b-cb5f323ddbb4-/var/cache/apt,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=s/9198bc32-97e7-4be3-944b-cb5f323ddbb4-/var/lib/apt,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libgcc-s1 \
    && rm -rf /var/lib/apt/lists/*;
RUN useradd -m -u 1000 appuser;
WORKDIR /home/appuser
COPY --from=builder /app/server ./server
USER appuser
EXPOSE $PORT
CMD ["./server"]
