default: run
run:
  PORT=$SYNC_SERVER_PORT go run .
migrate:
  bunx drizzle-kit generate
build:
  mkdir -p bin
  go build -o bin/sync-server .
fmt:
  go fmt ./...
lint:
  go vet ./...
test:
  go test ./...
