/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as SettingsProxyRouteImport } from './routes/settings/proxy'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ChatChatKeyRouteImport } from './routes/_chat/chat/$key'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProxyRoute = SettingsProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatChatKeyRoute = ChatChatKeyRouteImport.update({
  id: '/chat/$key',
  path: '/chat/$key',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/proxy': typeof SettingsProxyRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/chat/$key': typeof ChatChatKeyRoute
}
export interface FileRoutesByTo {
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/proxy': typeof SettingsProxyRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/chat/$key': typeof ChatChatKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/proxy': typeof SettingsProxyRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/_chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_chat/chat/$key': typeof ChatChatKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/mcp'
    | '/settings/providers'
    | '/settings/proxy'
    | '/settings/storage'
    | '/'
    | '/settings/'
    | '/chat/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/mcp'
    | '/settings/providers'
    | '/settings/proxy'
    | '/settings/storage'
    | '/'
    | '/settings'
    | '/chat/$key'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/mcp'
    | '/settings/providers'
    | '/settings/proxy'
    | '/settings/storage'
    | '/_chat/'
    | '/settings/'
    | '/_chat/chat/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/proxy': {
      id: '/settings/proxy'
      path: '/proxy'
      fullPath: '/settings/proxy'
      preLoaderRoute: typeof SettingsProxyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/chat/$key': {
      id: '/_chat/chat/$key'
      path: '/chat/$key'
      fullPath: '/chat/$key'
      preLoaderRoute: typeof ChatChatKeyRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatKeyRoute: typeof ChatChatKeyRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatChatKeyRoute: ChatChatKeyRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsProxyRoute: typeof SettingsProxyRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsProxyRoute: SettingsProxyRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
