// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file peers/v1/peer.proto (package peers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file peers/v1/peer.proto.
 */
export const file_peers_v1_peer: GenFile = /*@__PURE__*/
  fileDesc("ChNwZWVycy92MS9wZWVyLnByb3RvEghwZWVycy52MSIcCghUcmVlUGF0aBIQCghzZWdtZW50cxgBIAMoDSIgCg1TeW5jSGFuZHNoYWtlEg8KB3ZlcnNpb24YAiABKAkiTAoRTWVya2xlRGlnZXN0UXVlcnkSFAoMbWVya2xlX2RlcHRoGAEgASgNEiEKBXBhdGhzGAIgAygLMhIucGVlcnMudjEuVHJlZVBhdGgiLgoORGlnZXN0V2l0aFBhdGgSDAoEcGF0aBgBIAMoDRIOCgZkaWdlc3QYAiABKAwiVQoSTWVya2xlRGlnZXN0VXBkYXRlEhQKDG1lcmtsZV9kZXB0aBgBIAEoDRIpCgdkaWdlc3RzGAIgAygLMhgucGVlcnMudjEuRGlnZXN0V2l0aFBhdGgiPwoJUGVlckV2ZW50EhEKCXRpbWVzdGFtcBgBIAEoCRIRCglzaWduYXR1cmUYAiABKAkSDAoEZGF0YRgDIAEoDCIvChpIYXNFdmVudFdpdGhUaW1lc3RhbXBRdWVyeRIRCgl0aW1lc3RhbXAYASABKAkiPQobSGFzRXZlbnRXaXRoVGltZXN0YW1wVXBkYXRlEgsKA3llcxgBIAEoCBIRCgl0aW1lc3RhbXAYAiABKAkiMQoKRXZlbnRCYXRjaBIjCgZldmVudHMYASADKAsyEy5wZWVycy52MS5QZWVyRXZlbnQirAMKD1N5bmNXaXJlTWVzc2FnZRISCgphY2NvdW50X2lkGAEgASgJEhEKCWNsaWVudF9pZBgCIAEoCRIsCgloYW5kc2hha2UYAyABKAsyFy5wZWVycy52MS5TeW5jSGFuZHNoYWtlSAASMwoMZGlnZXN0X3F1ZXJ5GAQgASgLMhsucGVlcnMudjEuTWVya2xlRGlnZXN0UXVlcnlIABI1Cg1kaWdlc3RfdXBkYXRlGAUgASgLMhwucGVlcnMudjEuTWVya2xlRGlnZXN0VXBkYXRlSAASKwoLZXZlbnRfYmF0Y2gYBiABKAsyFC5wZWVycy52MS5FdmVudEJhdGNoSAASTgoeaGFzX2V2ZW50X3dpdGhfdGltZXN0YW1wX3F1ZXJ5GAcgASgLMiQucGVlcnMudjEuSGFzRXZlbnRXaXRoVGltZXN0YW1wUXVlcnlIABJQCh9oYXNfZXZlbnRfd2l0aF90aW1lc3RhbXBfdXBkYXRlGAggASgLMiUucGVlcnMudjEuSGFzRXZlbnRXaXRoVGltZXN0YW1wVXBkYXRlSABCCQoHcGF5bG9hZGIGcHJvdG8z");

/**
 * @generated from message peers.v1.TreePath
 */
export type TreePath = Message<"peers.v1.TreePath"> & {
  /**
   * @generated from field: repeated uint32 segments = 1;
   */
  segments: number[];
};

/**
 * Describes the message peers.v1.TreePath.
 * Use `create(TreePathSchema)` to create a new message.
 */
export const TreePathSchema: GenMessage<TreePath> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 0);

/**
 * @generated from message peers.v1.SyncHandshake
 */
export type SyncHandshake = Message<"peers.v1.SyncHandshake"> & {
  /**
   * @generated from field: string version = 2;
   */
  version: string;
};

/**
 * Describes the message peers.v1.SyncHandshake.
 * Use `create(SyncHandshakeSchema)` to create a new message.
 */
export const SyncHandshakeSchema: GenMessage<SyncHandshake> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 1);

/**
 * @generated from message peers.v1.MerkleDigestQuery
 */
export type MerkleDigestQuery = Message<"peers.v1.MerkleDigestQuery"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.TreePath paths = 2;
   */
  paths: TreePath[];
};

/**
 * Describes the message peers.v1.MerkleDigestQuery.
 * Use `create(MerkleDigestQuerySchema)` to create a new message.
 */
export const MerkleDigestQuerySchema: GenMessage<MerkleDigestQuery> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 2);

/**
 * @generated from message peers.v1.DigestWithPath
 */
export type DigestWithPath = Message<"peers.v1.DigestWithPath"> & {
  /**
   * @generated from field: repeated uint32 path = 1;
   */
  path: number[];

  /**
   * @generated from field: bytes digest = 2;
   */
  digest: Uint8Array;
};

/**
 * Describes the message peers.v1.DigestWithPath.
 * Use `create(DigestWithPathSchema)` to create a new message.
 */
export const DigestWithPathSchema: GenMessage<DigestWithPath> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 3);

/**
 * @generated from message peers.v1.MerkleDigestUpdate
 */
export type MerkleDigestUpdate = Message<"peers.v1.MerkleDigestUpdate"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.DigestWithPath digests = 2;
   */
  digests: DigestWithPath[];
};

/**
 * Describes the message peers.v1.MerkleDigestUpdate.
 * Use `create(MerkleDigestUpdateSchema)` to create a new message.
 */
export const MerkleDigestUpdateSchema: GenMessage<MerkleDigestUpdate> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 4);

/**
 * @generated from message peers.v1.PeerEvent
 */
export type PeerEvent = Message<"peers.v1.PeerEvent"> & {
  /**
   * @generated from field: string timestamp = 1;
   */
  timestamp: string;

  /**
   * @generated from field: string signature = 2;
   */
  signature: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message peers.v1.PeerEvent.
 * Use `create(PeerEventSchema)` to create a new message.
 */
export const PeerEventSchema: GenMessage<PeerEvent> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 5);

/**
 * @generated from message peers.v1.HasEventWithTimestampQuery
 */
export type HasEventWithTimestampQuery = Message<"peers.v1.HasEventWithTimestampQuery"> & {
  /**
   * @generated from field: string timestamp = 1;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.HasEventWithTimestampQuery.
 * Use `create(HasEventWithTimestampQuerySchema)` to create a new message.
 */
export const HasEventWithTimestampQuerySchema: GenMessage<HasEventWithTimestampQuery> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 6);

/**
 * @generated from message peers.v1.HasEventWithTimestampUpdate
 */
export type HasEventWithTimestampUpdate = Message<"peers.v1.HasEventWithTimestampUpdate"> & {
  /**
   * @generated from field: bool yes = 1;
   */
  yes: boolean;

  /**
   * @generated from field: string timestamp = 2;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.HasEventWithTimestampUpdate.
 * Use `create(HasEventWithTimestampUpdateSchema)` to create a new message.
 */
export const HasEventWithTimestampUpdateSchema: GenMessage<HasEventWithTimestampUpdate> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 7);

/**
 * @generated from message peers.v1.EventBatch
 */
export type EventBatch = Message<"peers.v1.EventBatch"> & {
  /**
   * @generated from field: repeated peers.v1.PeerEvent events = 1;
   */
  events: PeerEvent[];
};

/**
 * Describes the message peers.v1.EventBatch.
 * Use `create(EventBatchSchema)` to create a new message.
 */
export const EventBatchSchema: GenMessage<EventBatch> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 8);

/**
 * @generated from message peers.v1.SyncWireMessage
 */
export type SyncWireMessage = Message<"peers.v1.SyncWireMessage"> & {
  /**
   * @generated from field: string account_id = 1;
   */
  accountId: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from oneof peers.v1.SyncWireMessage.payload
   */
  payload: {
    /**
     * @generated from field: peers.v1.SyncHandshake handshake = 3;
     */
    value: SyncHandshake;
    case: "handshake";
  } | {
    /**
     * @generated from field: peers.v1.MerkleDigestQuery digest_query = 4;
     */
    value: MerkleDigestQuery;
    case: "digestQuery";
  } | {
    /**
     * @generated from field: peers.v1.MerkleDigestUpdate digest_update = 5;
     */
    value: MerkleDigestUpdate;
    case: "digestUpdate";
  } | {
    /**
     * @generated from field: peers.v1.EventBatch event_batch = 6;
     */
    value: EventBatch;
    case: "eventBatch";
  } | {
    /**
     * @generated from field: peers.v1.HasEventWithTimestampQuery has_event_with_timestamp_query = 7;
     */
    value: HasEventWithTimestampQuery;
    case: "hasEventWithTimestampQuery";
  } | {
    /**
     * @generated from field: peers.v1.HasEventWithTimestampUpdate has_event_with_timestamp_update = 8;
     */
    value: HasEventWithTimestampUpdate;
    case: "hasEventWithTimestampUpdate";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message peers.v1.SyncWireMessage.
 * Use `create(SyncWireMessageSchema)` to create a new message.
 */
export const SyncWireMessageSchema: GenMessage<SyncWireMessage> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 9);

