// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file peers/v1/backup.proto (package peers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file peers/v1/backup.proto.
 */
export const file_peers_v1_backup: GenFile = /*@__PURE__*/
  fileDesc("ChVwZWVycy92MS9iYWNrdXAucHJvdG8SCHBlZXJzLnYxIhgKCE1hbmlmZXN0EgwKBGRhdGEYASABKAwiDgoMU2VuZE1hbmlmZXN0IiAKBEJsb2ISCgoCaWQYASABKAkSDAoEZGF0YRgCIAEoDCImCgVCbG9icxIdCgVibG9icxgBIAMoCzIOLnBlZXJzLnYxLkJsb2IiGAoJU2VuZEJsb2JzEgsKA2lkcxgBIAMoCSIZCgpQcnVuZUJsb2JzEgsKA2lkcxgBIAMoCSLtAQoNQmFja3VwTWVzc2FnZRImCghtYW5pZmVzdBgBIAEoCzISLnBlZXJzLnYxLk1hbmlmZXN0SAASLwoNc2VuZF9tYW5pZmVzdBgCIAEoCzIWLnBlZXJzLnYxLlNlbmRNYW5pZmVzdEgAEiAKBWJsb2JzGAMgASgLMg8ucGVlcnMudjEuQmxvYnNIABIpCgpzZW5kX2Jsb2JzGAQgASgLMhMucGVlcnMudjEuU2VuZEJsb2JzSAASKwoLcHJ1bmVfYmxvYnMYBSABKAsyFC5wZWVycy52MS5QcnVuZUJsb2JzSABCCQoHbWVzc2FnZUIPWg1wcm90by9wZWVyc3BiYgZwcm90bzM");

/**
 * @generated from message peers.v1.Manifest
 */
export type Manifest = Message<"peers.v1.Manifest"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;
};

/**
 * Describes the message peers.v1.Manifest.
 * Use `create(ManifestSchema)` to create a new message.
 */
export const ManifestSchema: GenMessage<Manifest> = /*@__PURE__*/
  messageDesc(file_peers_v1_backup, 0);

/**
 * @generated from message peers.v1.SendManifest
 */
export type SendManifest = Message<"peers.v1.SendManifest"> & {
};

/**
 * Describes the message peers.v1.SendManifest.
 * Use `create(SendManifestSchema)` to create a new message.
 */
export const SendManifestSchema: GenMessage<SendManifest> = /*@__PURE__*/
  messageDesc(file_peers_v1_backup, 1);

/**
 * @generated from message peers.v1.Blob
 */
export type Blob = Message<"peers.v1.Blob"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message peers.v1.Blob.
 * Use `create(BlobSchema)` to create a new message.
 */
export const BlobSchema: GenMessage<Blob> = /*@__PURE__*/
  messageDesc(file_peers_v1_backup, 2);

/**
 * @generated from message peers.v1.Blobs
 */
export type Blobs = Message<"peers.v1.Blobs"> & {
  /**
   * @generated from field: repeated peers.v1.Blob blobs = 1;
   */
  blobs: Blob[];
};

/**
 * Describes the message peers.v1.Blobs.
 * Use `create(BlobsSchema)` to create a new message.
 */
export const BlobsSchema: GenMessage<Blobs> = /*@__PURE__*/
  messageDesc(file_peers_v1_backup, 3);

/**
 * @generated from message peers.v1.SendBlobs
 */
export type SendBlobs = Message<"peers.v1.SendBlobs"> & {
  /**
   * @generated from field: repeated string ids = 1;
   */
  ids: string[];
};

/**
 * Describes the message peers.v1.SendBlobs.
 * Use `create(SendBlobsSchema)` to create a new message.
 */
export const SendBlobsSchema: GenMessage<SendBlobs> = /*@__PURE__*/
  messageDesc(file_peers_v1_backup, 4);

/**
 * @generated from message peers.v1.PruneBlobs
 */
export type PruneBlobs = Message<"peers.v1.PruneBlobs"> & {
  /**
   * @generated from field: repeated string ids = 1;
   */
  ids: string[];
};

/**
 * Describes the message peers.v1.PruneBlobs.
 * Use `create(PruneBlobsSchema)` to create a new message.
 */
export const PruneBlobsSchema: GenMessage<PruneBlobs> = /*@__PURE__*/
  messageDesc(file_peers_v1_backup, 5);

/**
 * @generated from message peers.v1.BackupMessage
 */
export type BackupMessage = Message<"peers.v1.BackupMessage"> & {
  /**
   * @generated from oneof peers.v1.BackupMessage.message
   */
  message: {
    /**
     * @generated from field: peers.v1.Manifest manifest = 1;
     */
    value: Manifest;
    case: "manifest";
  } | {
    /**
     * @generated from field: peers.v1.SendManifest send_manifest = 2;
     */
    value: SendManifest;
    case: "sendManifest";
  } | {
    /**
     * @generated from field: peers.v1.Blobs blobs = 3;
     */
    value: Blobs;
    case: "blobs";
  } | {
    /**
     * @generated from field: peers.v1.SendBlobs send_blobs = 4;
     */
    value: SendBlobs;
    case: "sendBlobs";
  } | {
    /**
     * @generated from field: peers.v1.PruneBlobs prune_blobs = 5;
     */
    value: PruneBlobs;
    case: "pruneBlobs";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message peers.v1.BackupMessage.
 * Use `create(BackupMessageSchema)` to create a new message.
 */
export const BackupMessageSchema: GenMessage<BackupMessage> = /*@__PURE__*/
  messageDesc(file_peers_v1_backup, 6);

