// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file peers/v1/broadcast.proto (package peers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file peers/v1/broadcast.proto.
 */
export const file_peers_v1_broadcast: GenFile = /*@__PURE__*/
  fileDesc("ChhwZWVycy92MS9icm9hZGNhc3QucHJvdG8SCHBlZXJzLnYxIjkKB1B1Ymxpc2gSDQoFdG9waWMYASABKAkSEQoJc2lnbmF0dXJlGAIgASgJEgwKBGRhdGEYAyABKAwiGgoJU3Vic2NyaWJlEg0KBXRvcGljGAIgASgJIm0KEEJyb2FkY2FzdE1lc3NhZ2USJAoHcHVibGlzaBgBIAEoCzIRLnBlZXJzLnYxLlB1Ymxpc2hIABIoCglzdWJzY3JpYmUYAiABKAsyEy5wZWVycy52MS5TdWJzY3JpYmVIAEIJCgdtZXNzYWdlQg9aDXByb3RvL3BlZXJzcGJiBnByb3RvMw");

/**
 * @generated from message peers.v1.Publish
 */
export type Publish = Message<"peers.v1.Publish"> & {
  /**
   * @generated from field: string topic = 1;
   */
  topic: string;

  /**
   * @generated from field: string signature = 2;
   */
  signature: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message peers.v1.Publish.
 * Use `create(PublishSchema)` to create a new message.
 */
export const PublishSchema: GenMessage<Publish> = /*@__PURE__*/
  messageDesc(file_peers_v1_broadcast, 0);

/**
 * @generated from message peers.v1.Subscribe
 */
export type Subscribe = Message<"peers.v1.Subscribe"> & {
  /**
   * @generated from field: string topic = 2;
   */
  topic: string;
};

/**
 * Describes the message peers.v1.Subscribe.
 * Use `create(SubscribeSchema)` to create a new message.
 */
export const SubscribeSchema: GenMessage<Subscribe> = /*@__PURE__*/
  messageDesc(file_peers_v1_broadcast, 1);

/**
 * @generated from message peers.v1.BroadcastMessage
 */
export type BroadcastMessage = Message<"peers.v1.BroadcastMessage"> & {
  /**
   * @generated from oneof peers.v1.BroadcastMessage.message
   */
  message: {
    /**
     * @generated from field: peers.v1.Publish publish = 1;
     */
    value: Publish;
    case: "publish";
  } | {
    /**
     * @generated from field: peers.v1.Subscribe subscribe = 2;
     */
    value: Subscribe;
    case: "subscribe";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message peers.v1.BroadcastMessage.
 * Use `create(BroadcastMessageSchema)` to create a new message.
 */
export const BroadcastMessageSchema: GenMessage<BroadcastMessage> = /*@__PURE__*/
  messageDesc(file_peers_v1_broadcast, 2);

