// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file peers/v1/event_reconciliation.proto (package peers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file peers/v1/event_reconciliation.proto.
 */
export const file_peers_v1_event_reconciliation: GenFile = /*@__PURE__*/
  fileDesc("CiNwZWVycy92MS9ldmVudF9yZWNvbmNpbGlhdGlvbi5wcm90bxIIcGVlcnMudjEiOwoFRXZlbnQSDAoEZGF0YRgBIAEoDBIRCglzaWduYXR1cmUYAiABKAkSEQoJdGltZXN0YW1wGAMgASgJIikKBkV2ZW50cxIfCgZldmVudHMYASADKAsyDy5wZWVycy52MS5FdmVudCIgCgpTZW5kRXZlbnRzEhIKCnRpbWVzdGFtcHMYASADKAkiLQoYU2VuZEV2ZW50c0FmdGVyVGltZXN0YW1wEhEKCXRpbWVzdGFtcBgBIAEoCSInCgtQcnVuZUV2ZW50cxIYChBiZWZvcmVfdGltZXN0YW1wGAEgASgJIhsKC0RpZ2VzdFF1ZXJ5EgwKBHBhdGgYASADKA0iTQoNRGlnZXN0UXVlcmllcxIUCgxtZXJrbGVfZGVwdGgYASABKA0SJgoHcXVlcmllcxgCIAMoCzIVLnBlZXJzLnYxLkRpZ2VzdFF1ZXJ5Ij8KDERpZ2VzdFVwZGF0ZRIMCgRwYXRoGAEgAygNEg4KBmRpZ2VzdBgCIAEoDBIRCgl0aW1lc3RhbXAYAyABKAkiTgoNRGlnZXN0VXBkYXRlcxIUCgxtZXJrbGVfZGVwdGgYASABKA0SJwoHdXBkYXRlcxgCIAMoCzIWLnBlZXJzLnYxLkRpZ2VzdFVwZGF0ZSLYAgoaRXZlbnRSZWNvbmNpbGlhdGlvbk1lc3NhZ2USIgoGZXZlbnRzGAEgASgLMhAucGVlcnMudjEuRXZlbnRzSAASKwoLc2VuZF9ldmVudHMYAiABKAsyFC5wZWVycy52MS5TZW5kRXZlbnRzSAASSQobc2VuZF9ldmVudHNfYWZ0ZXJfdGltZXN0YW1wGAMgASgLMiIucGVlcnMudjEuU2VuZEV2ZW50c0FmdGVyVGltZXN0YW1wSAASLQoMcHJ1bmVfZXZlbnRzGAQgASgLMhUucGVlcnMudjEuUHJ1bmVFdmVudHNIABIxCg5kaWdlc3RfcXVlcmllcxgFIAEoCzIXLnBlZXJzLnYxLkRpZ2VzdFF1ZXJpZXNIABIxCg5kaWdlc3RfdXBkYXRlcxgGIAEoCzIXLnBlZXJzLnYxLkRpZ2VzdFVwZGF0ZXNIAEIJCgdtZXNzYWdlQg9aDXByb3RvL3BlZXJzcGJiBnByb3RvMw");

/**
 * @generated from message peers.v1.Event
 */
export type Event = Message<"peers.v1.Event"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;

  /**
   * @generated from field: string signature = 2;
   */
  signature: string;

  /**
   * @generated from field: string timestamp = 3;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 0);

/**
 * @generated from message peers.v1.Events
 */
export type Events = Message<"peers.v1.Events"> & {
  /**
   * @generated from field: repeated peers.v1.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message peers.v1.Events.
 * Use `create(EventsSchema)` to create a new message.
 */
export const EventsSchema: GenMessage<Events> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 1);

/**
 * @generated from message peers.v1.SendEvents
 */
export type SendEvents = Message<"peers.v1.SendEvents"> & {
  /**
   * @generated from field: repeated string timestamps = 1;
   */
  timestamps: string[];
};

/**
 * Describes the message peers.v1.SendEvents.
 * Use `create(SendEventsSchema)` to create a new message.
 */
export const SendEventsSchema: GenMessage<SendEvents> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 2);

/**
 * @generated from message peers.v1.SendEventsAfterTimestamp
 */
export type SendEventsAfterTimestamp = Message<"peers.v1.SendEventsAfterTimestamp"> & {
  /**
   * @generated from field: string timestamp = 1;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.SendEventsAfterTimestamp.
 * Use `create(SendEventsAfterTimestampSchema)` to create a new message.
 */
export const SendEventsAfterTimestampSchema: GenMessage<SendEventsAfterTimestamp> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 3);

/**
 * @generated from message peers.v1.PruneEvents
 */
export type PruneEvents = Message<"peers.v1.PruneEvents"> & {
  /**
   * @generated from field: string before_timestamp = 1;
   */
  beforeTimestamp: string;
};

/**
 * Describes the message peers.v1.PruneEvents.
 * Use `create(PruneEventsSchema)` to create a new message.
 */
export const PruneEventsSchema: GenMessage<PruneEvents> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 4);

/**
 * @generated from message peers.v1.DigestQuery
 */
export type DigestQuery = Message<"peers.v1.DigestQuery"> & {
  /**
   * @generated from field: repeated uint32 path = 1;
   */
  path: number[];
};

/**
 * Describes the message peers.v1.DigestQuery.
 * Use `create(DigestQuerySchema)` to create a new message.
 */
export const DigestQuerySchema: GenMessage<DigestQuery> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 5);

/**
 * @generated from message peers.v1.DigestQueries
 */
export type DigestQueries = Message<"peers.v1.DigestQueries"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.DigestQuery queries = 2;
   */
  queries: DigestQuery[];
};

/**
 * Describes the message peers.v1.DigestQueries.
 * Use `create(DigestQueriesSchema)` to create a new message.
 */
export const DigestQueriesSchema: GenMessage<DigestQueries> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 6);

/**
 * @generated from message peers.v1.DigestUpdate
 */
export type DigestUpdate = Message<"peers.v1.DigestUpdate"> & {
  /**
   * @generated from field: repeated uint32 path = 1;
   */
  path: number[];

  /**
   * @generated from field: bytes digest = 2;
   */
  digest: Uint8Array;

  /**
   * @generated from field: string timestamp = 3;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.DigestUpdate.
 * Use `create(DigestUpdateSchema)` to create a new message.
 */
export const DigestUpdateSchema: GenMessage<DigestUpdate> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 7);

/**
 * @generated from message peers.v1.DigestUpdates
 */
export type DigestUpdates = Message<"peers.v1.DigestUpdates"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.DigestUpdate updates = 2;
   */
  updates: DigestUpdate[];
};

/**
 * Describes the message peers.v1.DigestUpdates.
 * Use `create(DigestUpdatesSchema)` to create a new message.
 */
export const DigestUpdatesSchema: GenMessage<DigestUpdates> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 8);

/**
 * @generated from message peers.v1.EventReconciliationMessage
 */
export type EventReconciliationMessage = Message<"peers.v1.EventReconciliationMessage"> & {
  /**
   * @generated from oneof peers.v1.EventReconciliationMessage.message
   */
  message: {
    /**
     * @generated from field: peers.v1.Events events = 1;
     */
    value: Events;
    case: "events";
  } | {
    /**
     * @generated from field: peers.v1.SendEvents send_events = 2;
     */
    value: SendEvents;
    case: "sendEvents";
  } | {
    /**
     * @generated from field: peers.v1.SendEventsAfterTimestamp send_events_after_timestamp = 3;
     */
    value: SendEventsAfterTimestamp;
    case: "sendEventsAfterTimestamp";
  } | {
    /**
     * @generated from field: peers.v1.PruneEvents prune_events = 4;
     */
    value: PruneEvents;
    case: "pruneEvents";
  } | {
    /**
     * @generated from field: peers.v1.DigestQueries digest_queries = 5;
     */
    value: DigestQueries;
    case: "digestQueries";
  } | {
    /**
     * @generated from field: peers.v1.DigestUpdates digest_updates = 6;
     */
    value: DigestUpdates;
    case: "digestUpdates";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message peers.v1.EventReconciliationMessage.
 * Use `create(EventReconciliationMessageSchema)` to create a new message.
 */
export const EventReconciliationMessageSchema: GenMessage<EventReconciliationMessage> = /*@__PURE__*/
  messageDesc(file_peers_v1_event_reconciliation, 9);

