// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file peers/v1/peer.proto (package peers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file peers/v1/peer.proto.
 */
export const file_peers_v1_peer: GenFile = /*@__PURE__*/
  fileDesc("ChNwZWVycy92MS9wZWVyLnByb3RvEghwZWVycy52MSIcCghUcmVlUGF0aBIQCghzZWdtZW50cxgBIAMoDSJdCg1TeW5jSGFuZHNoYWtlEg8KB3ZlcnNpb24YAiABKAkSGAoLcm9vdF9kaWdlc3QYAyABKAxIAIgBARIRCgljbGllbnRfaWQYBCABKAlCDgoMX3Jvb3RfZGlnZXN0IkwKEU1lcmtsZURpZ2VzdFF1ZXJ5EhQKDG1lcmtsZV9kZXB0aBgBIAEoDRIhCgVwYXRocxgCIAMoCzISLnBlZXJzLnYxLlRyZWVQYXRoIi4KDkRpZ2VzdFdpdGhQYXRoEgwKBHBhdGgYASADKA0SDgoGZGlnZXN0GAIgASgMIlUKEk1lcmtsZURpZ2VzdFVwZGF0ZRIUCgxtZXJrbGVfZGVwdGgYASABKA0SKQoHZGlnZXN0cxgCIAMoCzIYLnBlZXJzLnYxLkRpZ2VzdFdpdGhQYXRoIj8KCVBlZXJFdmVudBIRCgl0aW1lc3RhbXAYASABKAkSEQoJc2lnbmF0dXJlGAIgASgJEgwKBGRhdGEYAyABKAwiMAoaSGFzRXZlbnRXaXRoVGltZXN0YW1wUXVlcnkSEgoKdGltZXN0YW1wcxgBIAMoCSIsChZTZW5kRXZlbnRXaXRoVGltZXN0YW1wEhIKCnRpbWVzdGFtcHMYASADKAkiPQobSGFzRXZlbnRXaXRoVGltZXN0YW1wVXBkYXRlEgsKA3llcxgBIAEoCBIRCgl0aW1lc3RhbXAYAiABKAkiVgocSGFzRXZlbnRXaXRoVGltZXN0YW1wVXBkYXRlcxI2Cgd1cGRhdGVzGAEgAygLMiUucGVlcnMudjEuSGFzRXZlbnRXaXRoVGltZXN0YW1wVXBkYXRlIjEKCkV2ZW50QmF0Y2gSIwoGZXZlbnRzGAEgAygLMhMucGVlcnMudjEuUGVlckV2ZW50IvUDCg9TeW5jV2lyZU1lc3NhZ2USEgoKYWNjb3VudF9pZBgBIAEoCRIRCgljbGllbnRfaWQYAiABKAkSLAoJaGFuZHNoYWtlGAMgASgLMhcucGVlcnMudjEuU3luY0hhbmRzaGFrZUgAEjMKDGRpZ2VzdF9xdWVyeRgEIAEoCzIbLnBlZXJzLnYxLk1lcmtsZURpZ2VzdFF1ZXJ5SAASNQoNZGlnZXN0X3VwZGF0ZRgFIAEoCzIcLnBlZXJzLnYxLk1lcmtsZURpZ2VzdFVwZGF0ZUgAEisKC2V2ZW50X2JhdGNoGAYgASgLMhQucGVlcnMudjEuRXZlbnRCYXRjaEgAEk4KHmhhc19ldmVudF93aXRoX3RpbWVzdGFtcF9xdWVyeRgHIAEoCzIkLnBlZXJzLnYxLkhhc0V2ZW50V2l0aFRpbWVzdGFtcFF1ZXJ5SAASUgogaGFzX2V2ZW50X3dpdGhfdGltZXN0YW1wX3VwZGF0ZXMYCCABKAsyJi5wZWVycy52MS5IYXNFdmVudFdpdGhUaW1lc3RhbXBVcGRhdGVzSAASRQoZc2VuZF9ldmVudF93aXRoX3RpbWVzdGFtcBgJIAEoCzIgLnBlZXJzLnYxLlNlbmRFdmVudFdpdGhUaW1lc3RhbXBIAEIJCgdwYXlsb2FkQg1aC3Byb3RvL3BlZXJzYgZwcm90bzM");

/**
 * @generated from message peers.v1.TreePath
 */
export type TreePath = Message<"peers.v1.TreePath"> & {
  /**
   * @generated from field: repeated uint32 segments = 1;
   */
  segments: number[];
};

/**
 * Describes the message peers.v1.TreePath.
 * Use `create(TreePathSchema)` to create a new message.
 */
export const TreePathSchema: GenMessage<TreePath> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 0);

/**
 * @generated from message peers.v1.SyncHandshake
 */
export type SyncHandshake = Message<"peers.v1.SyncHandshake"> & {
  /**
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * @generated from field: optional bytes root_digest = 3;
   */
  rootDigest?: Uint8Array | undefined;

  /**
   * @generated from field: string client_id = 4;
   */
  clientId: string;
};

/**
 * Describes the message peers.v1.SyncHandshake.
 * Use `create(SyncHandshakeSchema)` to create a new message.
 */
export const SyncHandshakeSchema: GenMessage<SyncHandshake> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 1);

/**
 * @generated from message peers.v1.MerkleDigestQuery
 */
export type MerkleDigestQuery = Message<"peers.v1.MerkleDigestQuery"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.TreePath paths = 2;
   */
  paths: TreePath[];
};

/**
 * Describes the message peers.v1.MerkleDigestQuery.
 * Use `create(MerkleDigestQuerySchema)` to create a new message.
 */
export const MerkleDigestQuerySchema: GenMessage<MerkleDigestQuery> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 2);

/**
 * @generated from message peers.v1.DigestWithPath
 */
export type DigestWithPath = Message<"peers.v1.DigestWithPath"> & {
  /**
   * @generated from field: repeated uint32 path = 1;
   */
  path: number[];

  /**
   * @generated from field: bytes digest = 2;
   */
  digest: Uint8Array;
};

/**
 * Describes the message peers.v1.DigestWithPath.
 * Use `create(DigestWithPathSchema)` to create a new message.
 */
export const DigestWithPathSchema: GenMessage<DigestWithPath> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 3);

/**
 * @generated from message peers.v1.MerkleDigestUpdate
 */
export type MerkleDigestUpdate = Message<"peers.v1.MerkleDigestUpdate"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.DigestWithPath digests = 2;
   */
  digests: DigestWithPath[];
};

/**
 * Describes the message peers.v1.MerkleDigestUpdate.
 * Use `create(MerkleDigestUpdateSchema)` to create a new message.
 */
export const MerkleDigestUpdateSchema: GenMessage<MerkleDigestUpdate> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 4);

/**
 * @generated from message peers.v1.PeerEvent
 */
export type PeerEvent = Message<"peers.v1.PeerEvent"> & {
  /**
   * @generated from field: string timestamp = 1;
   */
  timestamp: string;

  /**
   * @generated from field: string signature = 2;
   */
  signature: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message peers.v1.PeerEvent.
 * Use `create(PeerEventSchema)` to create a new message.
 */
export const PeerEventSchema: GenMessage<PeerEvent> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 5);

/**
 * @generated from message peers.v1.HasEventWithTimestampQuery
 */
export type HasEventWithTimestampQuery = Message<"peers.v1.HasEventWithTimestampQuery"> & {
  /**
   * @generated from field: repeated string timestamps = 1;
   */
  timestamps: string[];
};

/**
 * Describes the message peers.v1.HasEventWithTimestampQuery.
 * Use `create(HasEventWithTimestampQuerySchema)` to create a new message.
 */
export const HasEventWithTimestampQuerySchema: GenMessage<HasEventWithTimestampQuery> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 6);

/**
 * @generated from message peers.v1.SendEventWithTimestamp
 */
export type SendEventWithTimestamp = Message<"peers.v1.SendEventWithTimestamp"> & {
  /**
   * @generated from field: repeated string timestamps = 1;
   */
  timestamps: string[];
};

/**
 * Describes the message peers.v1.SendEventWithTimestamp.
 * Use `create(SendEventWithTimestampSchema)` to create a new message.
 */
export const SendEventWithTimestampSchema: GenMessage<SendEventWithTimestamp> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 7);

/**
 * @generated from message peers.v1.HasEventWithTimestampUpdate
 */
export type HasEventWithTimestampUpdate = Message<"peers.v1.HasEventWithTimestampUpdate"> & {
  /**
   * @generated from field: bool yes = 1;
   */
  yes: boolean;

  /**
   * @generated from field: string timestamp = 2;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.HasEventWithTimestampUpdate.
 * Use `create(HasEventWithTimestampUpdateSchema)` to create a new message.
 */
export const HasEventWithTimestampUpdateSchema: GenMessage<HasEventWithTimestampUpdate> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 8);

/**
 * @generated from message peers.v1.HasEventWithTimestampUpdates
 */
export type HasEventWithTimestampUpdates = Message<"peers.v1.HasEventWithTimestampUpdates"> & {
  /**
   * @generated from field: repeated peers.v1.HasEventWithTimestampUpdate updates = 1;
   */
  updates: HasEventWithTimestampUpdate[];
};

/**
 * Describes the message peers.v1.HasEventWithTimestampUpdates.
 * Use `create(HasEventWithTimestampUpdatesSchema)` to create a new message.
 */
export const HasEventWithTimestampUpdatesSchema: GenMessage<HasEventWithTimestampUpdates> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 9);

/**
 * @generated from message peers.v1.EventBatch
 */
export type EventBatch = Message<"peers.v1.EventBatch"> & {
  /**
   * @generated from field: repeated peers.v1.PeerEvent events = 1;
   */
  events: PeerEvent[];
};

/**
 * Describes the message peers.v1.EventBatch.
 * Use `create(EventBatchSchema)` to create a new message.
 */
export const EventBatchSchema: GenMessage<EventBatch> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 10);

/**
 * @generated from message peers.v1.SyncWireMessage
 */
export type SyncWireMessage = Message<"peers.v1.SyncWireMessage"> & {
  /**
   * @generated from field: string account_id = 1;
   */
  accountId: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from oneof peers.v1.SyncWireMessage.payload
   */
  payload: {
    /**
     * @generated from field: peers.v1.SyncHandshake handshake = 3;
     */
    value: SyncHandshake;
    case: "handshake";
  } | {
    /**
     * @generated from field: peers.v1.MerkleDigestQuery digest_query = 4;
     */
    value: MerkleDigestQuery;
    case: "digestQuery";
  } | {
    /**
     * @generated from field: peers.v1.MerkleDigestUpdate digest_update = 5;
     */
    value: MerkleDigestUpdate;
    case: "digestUpdate";
  } | {
    /**
     * @generated from field: peers.v1.EventBatch event_batch = 6;
     */
    value: EventBatch;
    case: "eventBatch";
  } | {
    /**
     * @generated from field: peers.v1.HasEventWithTimestampQuery has_event_with_timestamp_query = 7;
     */
    value: HasEventWithTimestampQuery;
    case: "hasEventWithTimestampQuery";
  } | {
    /**
     * @generated from field: peers.v1.HasEventWithTimestampUpdates has_event_with_timestamp_updates = 8;
     */
    value: HasEventWithTimestampUpdates;
    case: "hasEventWithTimestampUpdates";
  } | {
    /**
     * @generated from field: peers.v1.SendEventWithTimestamp send_event_with_timestamp = 9;
     */
    value: SendEventWithTimestamp;
    case: "sendEventWithTimestamp";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message peers.v1.SyncWireMessage.
 * Use `create(SyncWireMessageSchema)` to create a new message.
 */
export const SyncWireMessageSchema: GenMessage<SyncWireMessage> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 11);

