// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file peers/v1/peer.proto (package peers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file peers/v1/peer.proto.
 */
export const file_peers_v1_peer: GenFile = /*@__PURE__*/
  fileDesc("ChNwZWVycy92MS9wZWVyLnByb3RvEghwZWVycy52MSJdCg1TeW5jSGFuZHNoYWtlEg8KB3ZlcnNpb24YASABKAkSGAoLcm9vdF9kaWdlc3QYAiABKAxIAIgBARIRCgljbGllbnRfaWQYAyABKAlCDgoMX3Jvb3RfZGlnZXN0IhsKC0RpZ2VzdFF1ZXJ5EgwKBHBhdGgYASADKA0iTQoNRGlnZXN0UXVlcmllcxIUCgxtZXJrbGVfZGVwdGgYASABKA0SJgoHcXVlcmllcxgCIAMoCzIVLnBlZXJzLnYxLkRpZ2VzdFF1ZXJ5Ij8KDERpZ2VzdFVwZGF0ZRIMCgRwYXRoGAEgAygNEg4KBmRpZ2VzdBgCIAEoDBIRCgl0aW1lc3RhbXAYAyABKAkiTgoNRGlnZXN0VXBkYXRlcxIUCgxtZXJrbGVfZGVwdGgYASABKA0SJwoHdXBkYXRlcxgCIAMoCzIWLnBlZXJzLnYxLkRpZ2VzdFVwZGF0ZSJHChFFdmVudEJhdGNoUGF5bG9hZBIRCgl0aW1lc3RhbXAYASABKAkSEQoJc2lnbmF0dXJlGAIgASgJEgwKBGRhdGEYAyABKAwiLQoYU2VuZEV2ZW50c0FmdGVyVGltZXN0YW1wEhEKCXRpbWVzdGFtcBgBIAEoCSI5CgpFdmVudEJhdGNoEisKBmV2ZW50cxgBIAMoCzIbLnBlZXJzLnYxLkV2ZW50QmF0Y2hQYXlsb2FkIigKDFdlYlJUQ1NpZ25hbBIKCgJ0bxgBIAEoCRIMCgRkYXRhGAIgASgJIiIKDVBlZXJDb25uZWN0ZWQSEQoJY2xpZW50X2lkGAEgASgJIhoKB0FkZFBlZXISDwoHcGVlcl9pZBgBIAEoCSIdCgpSZW1vdmVQZWVyEg8KB3BlZXJfaWQYASABKAkihwQKD1N5bmNXaXJlTWVzc2FnZRISCgphY2NvdW50X2lkGAEgASgJEhEKCWNsaWVudF9pZBgCIAEoCRIsCgloYW5kc2hha2UYAyABKAsyFy5wZWVycy52MS5TeW5jSGFuZHNoYWtlSAASMQoOZGlnZXN0X3F1ZXJpZXMYBCABKAsyFy5wZWVycy52MS5EaWdlc3RRdWVyaWVzSAASMQoOZGlnZXN0X3VwZGF0ZXMYBSABKAsyFy5wZWVycy52MS5EaWdlc3RVcGRhdGVzSAASKwoLZXZlbnRfYmF0Y2gYBiABKAsyFC5wZWVycy52MS5FdmVudEJhdGNoSAASSQobc2VuZF9ldmVudHNfYWZ0ZXJfdGltZXN0YW1wGAcgASgLMiIucGVlcnMudjEuU2VuZEV2ZW50c0FmdGVyVGltZXN0YW1wSAASLwoNd2VicnRjX3NpZ25hbBgIIAEoCzIWLnBlZXJzLnYxLldlYlJUQ1NpZ25hbEgAEiUKCGFkZF9wZWVyGAkgASgLMhEucGVlcnMudjEuQWRkUGVlckgAEjEKDnBlZXJfY29ubmVjdGVkGAogASgLMhcucGVlcnMudjEuUGVlckNvbm5lY3RlZEgAEisKC3JlbW92ZV9wZWVyGAsgASgLMhQucGVlcnMudjEuUmVtb3ZlUGVlckgAQgkKB3BheWxvYWRCDVoLcHJvdG8vcGVlcnNiBnByb3RvMw");

/**
 * @generated from message peers.v1.SyncHandshake
 */
export type SyncHandshake = Message<"peers.v1.SyncHandshake"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: optional bytes root_digest = 2;
   */
  rootDigest?: Uint8Array | undefined;

  /**
   * @generated from field: string client_id = 3;
   */
  clientId: string;
};

/**
 * Describes the message peers.v1.SyncHandshake.
 * Use `create(SyncHandshakeSchema)` to create a new message.
 */
export const SyncHandshakeSchema: GenMessage<SyncHandshake> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 0);

/**
 * @generated from message peers.v1.DigestQuery
 */
export type DigestQuery = Message<"peers.v1.DigestQuery"> & {
  /**
   * @generated from field: repeated uint32 path = 1;
   */
  path: number[];
};

/**
 * Describes the message peers.v1.DigestQuery.
 * Use `create(DigestQuerySchema)` to create a new message.
 */
export const DigestQuerySchema: GenMessage<DigestQuery> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 1);

/**
 * @generated from message peers.v1.DigestQueries
 */
export type DigestQueries = Message<"peers.v1.DigestQueries"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.DigestQuery queries = 2;
   */
  queries: DigestQuery[];
};

/**
 * Describes the message peers.v1.DigestQueries.
 * Use `create(DigestQueriesSchema)` to create a new message.
 */
export const DigestQueriesSchema: GenMessage<DigestQueries> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 2);

/**
 * @generated from message peers.v1.DigestUpdate
 */
export type DigestUpdate = Message<"peers.v1.DigestUpdate"> & {
  /**
   * @generated from field: repeated uint32 path = 1;
   */
  path: number[];

  /**
   * @generated from field: bytes digest = 2;
   */
  digest: Uint8Array;

  /**
   * @generated from field: string timestamp = 3;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.DigestUpdate.
 * Use `create(DigestUpdateSchema)` to create a new message.
 */
export const DigestUpdateSchema: GenMessage<DigestUpdate> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 3);

/**
 * @generated from message peers.v1.DigestUpdates
 */
export type DigestUpdates = Message<"peers.v1.DigestUpdates"> & {
  /**
   * @generated from field: uint32 merkle_depth = 1;
   */
  merkleDepth: number;

  /**
   * @generated from field: repeated peers.v1.DigestUpdate updates = 2;
   */
  updates: DigestUpdate[];
};

/**
 * Describes the message peers.v1.DigestUpdates.
 * Use `create(DigestUpdatesSchema)` to create a new message.
 */
export const DigestUpdatesSchema: GenMessage<DigestUpdates> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 4);

/**
 * @generated from message peers.v1.EventBatchPayload
 */
export type EventBatchPayload = Message<"peers.v1.EventBatchPayload"> & {
  /**
   * @generated from field: string timestamp = 1;
   */
  timestamp: string;

  /**
   * @generated from field: string signature = 2;
   */
  signature: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message peers.v1.EventBatchPayload.
 * Use `create(EventBatchPayloadSchema)` to create a new message.
 */
export const EventBatchPayloadSchema: GenMessage<EventBatchPayload> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 5);

/**
 * @generated from message peers.v1.SendEventsAfterTimestamp
 */
export type SendEventsAfterTimestamp = Message<"peers.v1.SendEventsAfterTimestamp"> & {
  /**
   * @generated from field: string timestamp = 1;
   */
  timestamp: string;
};

/**
 * Describes the message peers.v1.SendEventsAfterTimestamp.
 * Use `create(SendEventsAfterTimestampSchema)` to create a new message.
 */
export const SendEventsAfterTimestampSchema: GenMessage<SendEventsAfterTimestamp> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 6);

/**
 * @generated from message peers.v1.EventBatch
 */
export type EventBatch = Message<"peers.v1.EventBatch"> & {
  /**
   * @generated from field: repeated peers.v1.EventBatchPayload events = 1;
   */
  events: EventBatchPayload[];
};

/**
 * Describes the message peers.v1.EventBatch.
 * Use `create(EventBatchSchema)` to create a new message.
 */
export const EventBatchSchema: GenMessage<EventBatch> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 7);

/**
 * @generated from message peers.v1.WebRTCSignal
 */
export type WebRTCSignal = Message<"peers.v1.WebRTCSignal"> & {
  /**
   * @generated from field: string to = 1;
   */
  to: string;

  /**
   * @generated from field: string data = 2;
   */
  data: string;
};

/**
 * Describes the message peers.v1.WebRTCSignal.
 * Use `create(WebRTCSignalSchema)` to create a new message.
 */
export const WebRTCSignalSchema: GenMessage<WebRTCSignal> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 8);

/**
 * @generated from message peers.v1.PeerConnected
 */
export type PeerConnected = Message<"peers.v1.PeerConnected"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;
};

/**
 * Describes the message peers.v1.PeerConnected.
 * Use `create(PeerConnectedSchema)` to create a new message.
 */
export const PeerConnectedSchema: GenMessage<PeerConnected> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 9);

/**
 * @generated from message peers.v1.AddPeer
 */
export type AddPeer = Message<"peers.v1.AddPeer"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;
};

/**
 * Describes the message peers.v1.AddPeer.
 * Use `create(AddPeerSchema)` to create a new message.
 */
export const AddPeerSchema: GenMessage<AddPeer> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 10);

/**
 * @generated from message peers.v1.RemovePeer
 */
export type RemovePeer = Message<"peers.v1.RemovePeer"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;
};

/**
 * Describes the message peers.v1.RemovePeer.
 * Use `create(RemovePeerSchema)` to create a new message.
 */
export const RemovePeerSchema: GenMessage<RemovePeer> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 11);

/**
 * @generated from message peers.v1.SyncWireMessage
 */
export type SyncWireMessage = Message<"peers.v1.SyncWireMessage"> & {
  /**
   * @generated from field: string account_id = 1;
   */
  accountId: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from oneof peers.v1.SyncWireMessage.payload
   */
  payload: {
    /**
     * @generated from field: peers.v1.SyncHandshake handshake = 3;
     */
    value: SyncHandshake;
    case: "handshake";
  } | {
    /**
     * @generated from field: peers.v1.DigestQueries digest_queries = 4;
     */
    value: DigestQueries;
    case: "digestQueries";
  } | {
    /**
     * @generated from field: peers.v1.DigestUpdates digest_updates = 5;
     */
    value: DigestUpdates;
    case: "digestUpdates";
  } | {
    /**
     * @generated from field: peers.v1.EventBatch event_batch = 6;
     */
    value: EventBatch;
    case: "eventBatch";
  } | {
    /**
     * @generated from field: peers.v1.SendEventsAfterTimestamp send_events_after_timestamp = 7;
     */
    value: SendEventsAfterTimestamp;
    case: "sendEventsAfterTimestamp";
  } | {
    /**
     * @generated from field: peers.v1.WebRTCSignal webrtc_signal = 8;
     */
    value: WebRTCSignal;
    case: "webrtcSignal";
  } | {
    /**
     * @generated from field: peers.v1.AddPeer add_peer = 9;
     */
    value: AddPeer;
    case: "addPeer";
  } | {
    /**
     * @generated from field: peers.v1.PeerConnected peer_connected = 10;
     */
    value: PeerConnected;
    case: "peerConnected";
  } | {
    /**
     * @generated from field: peers.v1.RemovePeer remove_peer = 11;
     */
    value: RemovePeer;
    case: "removePeer";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message peers.v1.SyncWireMessage.
 * Use `create(SyncWireMessageSchema)` to create a new message.
 */
export const SyncWireMessageSchema: GenMessage<SyncWireMessage> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 12);

