// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file peers/v1/peer.proto (package peers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BackupMessage } from "./backup_pb";
import { file_peers_v1_backup } from "./backup_pb";
import type { BroadcastMessage } from "./broadcast_pb";
import { file_peers_v1_broadcast } from "./broadcast_pb";
import type { EventReconciliationMessage } from "./event_reconciliation_pb";
import { file_peers_v1_event_reconciliation } from "./event_reconciliation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file peers/v1/peer.proto.
 */
export const file_peers_v1_peer: GenFile = /*@__PURE__*/
  fileDesc("ChNwZWVycy92MS9wZWVyLnByb3RvEghwZWVycy52MSJPCgxDYXBhYmlsaXRpZXMSDgoGYmFja3VwGAEgASgIEhEKCWJyb2FkY2FzdBgCIAEoCBIcChRldmVudF9yZWNvbmNpbGlhdGlvbhgDIAEoCCI5CglIYW5kc2hha2USLAoMY2FwYWJpbGl0aWVzGAMgASgLMhYucGVlcnMudjEuQ2FwYWJpbGl0aWVzIvsBChJQZWVyTWVzc2FnZVBheWxvYWQSKAoJaGFuZHNoYWtlGAMgASgLMhMucGVlcnMudjEuSGFuZHNoYWtlSAASMQoOYmFja3VwX21lc3NhZ2UYBCABKAsyFy5wZWVycy52MS5CYWNrdXBNZXNzYWdlSAASNwoRYnJvYWRjYXN0X21lc3NhZ2UYBSABKAsyGi5wZWVycy52MS5Ccm9hZGNhc3RNZXNzYWdlSAASRAoUZXZlbnRfcmVjb25jaWxpYXRpb24YBiABKAsyJC5wZWVycy52MS5FdmVudFJlY29uY2lsaWF0aW9uTWVzc2FnZUgAQgkKB3BheWxvYWQiYwoLUGVlck1lc3NhZ2USEgoKYWNjb3VudF9pZBgBIAEoCRIRCgljbGllbnRfaWQYAiABKAkSLQoHbWVzc2FnZRgDIAEoCzIcLnBlZXJzLnYxLlBlZXJNZXNzYWdlUGF5bG9hZEIPWg1wcm90by9wZWVyc3BiYgZwcm90bzM", [file_peers_v1_backup, file_peers_v1_broadcast, file_peers_v1_event_reconciliation]);

/**
 * @generated from message peers.v1.Capabilities
 */
export type Capabilities = Message<"peers.v1.Capabilities"> & {
  /**
   * @generated from field: bool backup = 1;
   */
  backup: boolean;

  /**
   * @generated from field: bool broadcast = 2;
   */
  broadcast: boolean;

  /**
   * @generated from field: bool event_reconciliation = 3;
   */
  eventReconciliation: boolean;
};

/**
 * Describes the message peers.v1.Capabilities.
 * Use `create(CapabilitiesSchema)` to create a new message.
 */
export const CapabilitiesSchema: GenMessage<Capabilities> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 0);

/**
 * @generated from message peers.v1.Handshake
 */
export type Handshake = Message<"peers.v1.Handshake"> & {
  /**
   * @generated from field: peers.v1.Capabilities capabilities = 3;
   */
  capabilities?: Capabilities | undefined;
};

/**
 * Describes the message peers.v1.Handshake.
 * Use `create(HandshakeSchema)` to create a new message.
 */
export const HandshakeSchema: GenMessage<Handshake> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 1);

/**
 * @generated from message peers.v1.PeerMessagePayload
 */
export type PeerMessagePayload = Message<"peers.v1.PeerMessagePayload"> & {
  /**
   * @generated from oneof peers.v1.PeerMessagePayload.payload
   */
  payload: {
    /**
     * @generated from field: peers.v1.Handshake handshake = 3;
     */
    value: Handshake;
    case: "handshake";
  } | {
    /**
     * @generated from field: peers.v1.BackupMessage backup_message = 4;
     */
    value: BackupMessage;
    case: "backupMessage";
  } | {
    /**
     * @generated from field: peers.v1.BroadcastMessage broadcast_message = 5;
     */
    value: BroadcastMessage;
    case: "broadcastMessage";
  } | {
    /**
     * @generated from field: peers.v1.EventReconciliationMessage event_reconciliation = 6;
     */
    value: EventReconciliationMessage;
    case: "eventReconciliation";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message peers.v1.PeerMessagePayload.
 * Use `create(PeerMessagePayloadSchema)` to create a new message.
 */
export const PeerMessagePayloadSchema: GenMessage<PeerMessagePayload> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 2);

/**
 * @generated from message peers.v1.PeerMessage
 */
export type PeerMessage = Message<"peers.v1.PeerMessage"> & {
  /**
   * @generated from field: string account_id = 1;
   */
  accountId: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: peers.v1.PeerMessagePayload message = 3;
   */
  message?: PeerMessagePayload | undefined;
};

/**
 * Describes the message peers.v1.PeerMessage.
 * Use `create(PeerMessageSchema)` to create a new message.
 */
export const PeerMessageSchema: GenMessage<PeerMessage> = /*@__PURE__*/
  messageDesc(file_peers_v1_peer, 3);

