// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peers/v1/backup.proto

package peerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_peers_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_peers_v1_backup_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendManifest) Reset() {
	*x = SendManifest{}
	mi := &file_peers_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendManifest) ProtoMessage() {}

func (x *SendManifest) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendManifest.ProtoReflect.Descriptor instead.
func (*SendManifest) Descriptor() ([]byte, []int) {
	return file_peers_v1_backup_proto_rawDescGZIP(), []int{1}
}

type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_peers_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_peers_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *Blob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Blobs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blobs         []*Blob                `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blobs) Reset() {
	*x = Blobs{}
	mi := &file_peers_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blobs) ProtoMessage() {}

func (x *Blobs) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blobs.ProtoReflect.Descriptor instead.
func (*Blobs) Descriptor() ([]byte, []int) {
	return file_peers_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *Blobs) GetBlobs() []*Blob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

type SendBlobs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBlobs) Reset() {
	*x = SendBlobs{}
	mi := &file_peers_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBlobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlobs) ProtoMessage() {}

func (x *SendBlobs) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlobs.ProtoReflect.Descriptor instead.
func (*SendBlobs) Descriptor() ([]byte, []int) {
	return file_peers_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *SendBlobs) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PruneBlobs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneBlobs) Reset() {
	*x = PruneBlobs{}
	mi := &file_peers_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneBlobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneBlobs) ProtoMessage() {}

func (x *PruneBlobs) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneBlobs.ProtoReflect.Descriptor instead.
func (*PruneBlobs) Descriptor() ([]byte, []int) {
	return file_peers_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *PruneBlobs) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BackupMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*BackupMessage_Manifest
	//	*BackupMessage_SendManifest
	//	*BackupMessage_Blobs
	//	*BackupMessage_SendBlobs
	//	*BackupMessage_PruneBlobs
	Message       isBackupMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupMessage) Reset() {
	*x = BackupMessage{}
	mi := &file_peers_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupMessage) ProtoMessage() {}

func (x *BackupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupMessage.ProtoReflect.Descriptor instead.
func (*BackupMessage) Descriptor() ([]byte, []int) {
	return file_peers_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupMessage) GetMessage() isBackupMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BackupMessage) GetManifest() *Manifest {
	if x != nil {
		if x, ok := x.Message.(*BackupMessage_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *BackupMessage) GetSendManifest() *SendManifest {
	if x != nil {
		if x, ok := x.Message.(*BackupMessage_SendManifest); ok {
			return x.SendManifest
		}
	}
	return nil
}

func (x *BackupMessage) GetBlobs() *Blobs {
	if x != nil {
		if x, ok := x.Message.(*BackupMessage_Blobs); ok {
			return x.Blobs
		}
	}
	return nil
}

func (x *BackupMessage) GetSendBlobs() *SendBlobs {
	if x != nil {
		if x, ok := x.Message.(*BackupMessage_SendBlobs); ok {
			return x.SendBlobs
		}
	}
	return nil
}

func (x *BackupMessage) GetPruneBlobs() *PruneBlobs {
	if x != nil {
		if x, ok := x.Message.(*BackupMessage_PruneBlobs); ok {
			return x.PruneBlobs
		}
	}
	return nil
}

type isBackupMessage_Message interface {
	isBackupMessage_Message()
}

type BackupMessage_Manifest struct {
	Manifest *Manifest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"`
}

type BackupMessage_SendManifest struct {
	SendManifest *SendManifest `protobuf:"bytes,2,opt,name=send_manifest,json=sendManifest,proto3,oneof"`
}

type BackupMessage_Blobs struct {
	Blobs *Blobs `protobuf:"bytes,3,opt,name=blobs,proto3,oneof"`
}

type BackupMessage_SendBlobs struct {
	SendBlobs *SendBlobs `protobuf:"bytes,4,opt,name=send_blobs,json=sendBlobs,proto3,oneof"`
}

type BackupMessage_PruneBlobs struct {
	PruneBlobs *PruneBlobs `protobuf:"bytes,5,opt,name=prune_blobs,json=pruneBlobs,proto3,oneof"`
}

func (*BackupMessage_Manifest) isBackupMessage_Message() {}

func (*BackupMessage_SendManifest) isBackupMessage_Message() {}

func (*BackupMessage_Blobs) isBackupMessage_Message() {}

func (*BackupMessage_SendBlobs) isBackupMessage_Message() {}

func (*BackupMessage_PruneBlobs) isBackupMessage_Message() {}

var File_peers_v1_backup_proto protoreflect.FileDescriptor

const file_peers_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x15peers/v1/backup.proto\x12\bpeers.v1\"\x1e\n" +
	"\bManifest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x0e\n" +
	"\fSendManifest\"*\n" +
	"\x04Blob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"-\n" +
	"\x05Blobs\x12$\n" +
	"\x05blobs\x18\x01 \x03(\v2\x0e.peers.v1.BlobR\x05blobs\"\x1d\n" +
	"\tSendBlobs\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x1e\n" +
	"\n" +
	"PruneBlobs\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xa3\x02\n" +
	"\rBackupMessage\x120\n" +
	"\bmanifest\x18\x01 \x01(\v2\x12.peers.v1.ManifestH\x00R\bmanifest\x12=\n" +
	"\rsend_manifest\x18\x02 \x01(\v2\x16.peers.v1.SendManifestH\x00R\fsendManifest\x12'\n" +
	"\x05blobs\x18\x03 \x01(\v2\x0f.peers.v1.BlobsH\x00R\x05blobs\x124\n" +
	"\n" +
	"send_blobs\x18\x04 \x01(\v2\x13.peers.v1.SendBlobsH\x00R\tsendBlobs\x127\n" +
	"\vprune_blobs\x18\x05 \x01(\v2\x14.peers.v1.PruneBlobsH\x00R\n" +
	"pruneBlobsB\t\n" +
	"\amessageB\x0fZ\rproto/peerspbb\x06proto3"

var (
	file_peers_v1_backup_proto_rawDescOnce sync.Once
	file_peers_v1_backup_proto_rawDescData []byte
)

func file_peers_v1_backup_proto_rawDescGZIP() []byte {
	file_peers_v1_backup_proto_rawDescOnce.Do(func() {
		file_peers_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peers_v1_backup_proto_rawDesc), len(file_peers_v1_backup_proto_rawDesc)))
	})
	return file_peers_v1_backup_proto_rawDescData
}

var file_peers_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_peers_v1_backup_proto_goTypes = []any{
	(*Manifest)(nil),      // 0: peers.v1.Manifest
	(*SendManifest)(nil),  // 1: peers.v1.SendManifest
	(*Blob)(nil),          // 2: peers.v1.Blob
	(*Blobs)(nil),         // 3: peers.v1.Blobs
	(*SendBlobs)(nil),     // 4: peers.v1.SendBlobs
	(*PruneBlobs)(nil),    // 5: peers.v1.PruneBlobs
	(*BackupMessage)(nil), // 6: peers.v1.BackupMessage
}
var file_peers_v1_backup_proto_depIdxs = []int32{
	2, // 0: peers.v1.Blobs.blobs:type_name -> peers.v1.Blob
	0, // 1: peers.v1.BackupMessage.manifest:type_name -> peers.v1.Manifest
	1, // 2: peers.v1.BackupMessage.send_manifest:type_name -> peers.v1.SendManifest
	3, // 3: peers.v1.BackupMessage.blobs:type_name -> peers.v1.Blobs
	4, // 4: peers.v1.BackupMessage.send_blobs:type_name -> peers.v1.SendBlobs
	5, // 5: peers.v1.BackupMessage.prune_blobs:type_name -> peers.v1.PruneBlobs
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_peers_v1_backup_proto_init() }
func file_peers_v1_backup_proto_init() {
	if File_peers_v1_backup_proto != nil {
		return
	}
	file_peers_v1_backup_proto_msgTypes[6].OneofWrappers = []any{
		(*BackupMessage_Manifest)(nil),
		(*BackupMessage_SendManifest)(nil),
		(*BackupMessage_Blobs)(nil),
		(*BackupMessage_SendBlobs)(nil),
		(*BackupMessage_PruneBlobs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peers_v1_backup_proto_rawDesc), len(file_peers_v1_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peers_v1_backup_proto_goTypes,
		DependencyIndexes: file_peers_v1_backup_proto_depIdxs,
		MessageInfos:      file_peers_v1_backup_proto_msgTypes,
	}.Build()
	File_peers_v1_backup_proto = out.File
	file_peers_v1_backup_proto_goTypes = nil
	file_peers_v1_backup_proto_depIdxs = nil
}
