// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peers/v1/event_reconciliation.proto

package peerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{1}
}

func (x *Events) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type SendEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamps    []string               `protobuf:"bytes,1,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEvents) Reset() {
	*x = SendEvents{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEvents) ProtoMessage() {}

func (x *SendEvents) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEvents.ProtoReflect.Descriptor instead.
func (*SendEvents) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{2}
}

func (x *SendEvents) GetTimestamps() []string {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type SendEventsAfterTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventsAfterTimestamp) Reset() {
	*x = SendEventsAfterTimestamp{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventsAfterTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventsAfterTimestamp) ProtoMessage() {}

func (x *SendEventsAfterTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventsAfterTimestamp.ProtoReflect.Descriptor instead.
func (*SendEventsAfterTimestamp) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{3}
}

func (x *SendEventsAfterTimestamp) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PruneEvents struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BeforeTimestamp string                 `protobuf:"bytes,1,opt,name=before_timestamp,json=beforeTimestamp,proto3" json:"before_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PruneEvents) Reset() {
	*x = PruneEvents{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneEvents) ProtoMessage() {}

func (x *PruneEvents) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneEvents.ProtoReflect.Descriptor instead.
func (*PruneEvents) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{4}
}

func (x *PruneEvents) GetBeforeTimestamp() string {
	if x != nil {
		return x.BeforeTimestamp
	}
	return ""
}

type DigestQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []uint32               `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestQuery) Reset() {
	*x = DigestQuery{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestQuery) ProtoMessage() {}

func (x *DigestQuery) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestQuery.ProtoReflect.Descriptor instead.
func (*DigestQuery) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{5}
}

func (x *DigestQuery) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

type DigestQueries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleDepth   uint32                 `protobuf:"varint,1,opt,name=merkle_depth,json=merkleDepth,proto3" json:"merkle_depth,omitempty"`
	Queries       []*DigestQuery         `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestQueries) Reset() {
	*x = DigestQueries{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestQueries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestQueries) ProtoMessage() {}

func (x *DigestQueries) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestQueries.ProtoReflect.Descriptor instead.
func (*DigestQueries) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{6}
}

func (x *DigestQueries) GetMerkleDepth() uint32 {
	if x != nil {
		return x.MerkleDepth
	}
	return 0
}

func (x *DigestQueries) GetQueries() []*DigestQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type DigestUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []uint32               `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestUpdate) Reset() {
	*x = DigestUpdate{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestUpdate) ProtoMessage() {}

func (x *DigestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestUpdate.ProtoReflect.Descriptor instead.
func (*DigestUpdate) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{7}
}

func (x *DigestUpdate) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *DigestUpdate) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *DigestUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type DigestUpdates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleDepth   uint32                 `protobuf:"varint,1,opt,name=merkle_depth,json=merkleDepth,proto3" json:"merkle_depth,omitempty"`
	Updates       []*DigestUpdate        `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestUpdates) Reset() {
	*x = DigestUpdates{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestUpdates) ProtoMessage() {}

func (x *DigestUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestUpdates.ProtoReflect.Descriptor instead.
func (*DigestUpdates) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{8}
}

func (x *DigestUpdates) GetMerkleDepth() uint32 {
	if x != nil {
		return x.MerkleDepth
	}
	return 0
}

func (x *DigestUpdates) GetUpdates() []*DigestUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type EventReconciliationMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*EventReconciliationMessage_Events
	//	*EventReconciliationMessage_SendEvents
	//	*EventReconciliationMessage_SendEventsAfterTimestamp
	//	*EventReconciliationMessage_PruneEvents
	//	*EventReconciliationMessage_DigestQueries
	//	*EventReconciliationMessage_DigestUpdates
	Message       isEventReconciliationMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReconciliationMessage) Reset() {
	*x = EventReconciliationMessage{}
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReconciliationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReconciliationMessage) ProtoMessage() {}

func (x *EventReconciliationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_event_reconciliation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReconciliationMessage.ProtoReflect.Descriptor instead.
func (*EventReconciliationMessage) Descriptor() ([]byte, []int) {
	return file_peers_v1_event_reconciliation_proto_rawDescGZIP(), []int{9}
}

func (x *EventReconciliationMessage) GetMessage() isEventReconciliationMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *EventReconciliationMessage) GetEvents() *Events {
	if x != nil {
		if x, ok := x.Message.(*EventReconciliationMessage_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *EventReconciliationMessage) GetSendEvents() *SendEvents {
	if x != nil {
		if x, ok := x.Message.(*EventReconciliationMessage_SendEvents); ok {
			return x.SendEvents
		}
	}
	return nil
}

func (x *EventReconciliationMessage) GetSendEventsAfterTimestamp() *SendEventsAfterTimestamp {
	if x != nil {
		if x, ok := x.Message.(*EventReconciliationMessage_SendEventsAfterTimestamp); ok {
			return x.SendEventsAfterTimestamp
		}
	}
	return nil
}

func (x *EventReconciliationMessage) GetPruneEvents() *PruneEvents {
	if x != nil {
		if x, ok := x.Message.(*EventReconciliationMessage_PruneEvents); ok {
			return x.PruneEvents
		}
	}
	return nil
}

func (x *EventReconciliationMessage) GetDigestQueries() *DigestQueries {
	if x != nil {
		if x, ok := x.Message.(*EventReconciliationMessage_DigestQueries); ok {
			return x.DigestQueries
		}
	}
	return nil
}

func (x *EventReconciliationMessage) GetDigestUpdates() *DigestUpdates {
	if x != nil {
		if x, ok := x.Message.(*EventReconciliationMessage_DigestUpdates); ok {
			return x.DigestUpdates
		}
	}
	return nil
}

type isEventReconciliationMessage_Message interface {
	isEventReconciliationMessage_Message()
}

type EventReconciliationMessage_Events struct {
	Events *Events `protobuf:"bytes,1,opt,name=events,proto3,oneof"`
}

type EventReconciliationMessage_SendEvents struct {
	SendEvents *SendEvents `protobuf:"bytes,2,opt,name=send_events,json=sendEvents,proto3,oneof"`
}

type EventReconciliationMessage_SendEventsAfterTimestamp struct {
	SendEventsAfterTimestamp *SendEventsAfterTimestamp `protobuf:"bytes,3,opt,name=send_events_after_timestamp,json=sendEventsAfterTimestamp,proto3,oneof"`
}

type EventReconciliationMessage_PruneEvents struct {
	PruneEvents *PruneEvents `protobuf:"bytes,4,opt,name=prune_events,json=pruneEvents,proto3,oneof"`
}

type EventReconciliationMessage_DigestQueries struct {
	DigestQueries *DigestQueries `protobuf:"bytes,5,opt,name=digest_queries,json=digestQueries,proto3,oneof"`
}

type EventReconciliationMessage_DigestUpdates struct {
	DigestUpdates *DigestUpdates `protobuf:"bytes,6,opt,name=digest_updates,json=digestUpdates,proto3,oneof"`
}

func (*EventReconciliationMessage_Events) isEventReconciliationMessage_Message() {}

func (*EventReconciliationMessage_SendEvents) isEventReconciliationMessage_Message() {}

func (*EventReconciliationMessage_SendEventsAfterTimestamp) isEventReconciliationMessage_Message() {}

func (*EventReconciliationMessage_PruneEvents) isEventReconciliationMessage_Message() {}

func (*EventReconciliationMessage_DigestQueries) isEventReconciliationMessage_Message() {}

func (*EventReconciliationMessage_DigestUpdates) isEventReconciliationMessage_Message() {}

var File_peers_v1_event_reconciliation_proto protoreflect.FileDescriptor

const file_peers_v1_event_reconciliation_proto_rawDesc = "" +
	"\n" +
	"#peers/v1/event_reconciliation.proto\x12\bpeers.v1\"W\n" +
	"\x05Event\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"1\n" +
	"\x06Events\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.peers.v1.EventR\x06events\",\n" +
	"\n" +
	"SendEvents\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x01 \x03(\tR\n" +
	"timestamps\"8\n" +
	"\x18SendEventsAfterTimestamp\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\"8\n" +
	"\vPruneEvents\x12)\n" +
	"\x10before_timestamp\x18\x01 \x01(\tR\x0fbeforeTimestamp\"!\n" +
	"\vDigestQuery\x12\x12\n" +
	"\x04path\x18\x01 \x03(\rR\x04path\"c\n" +
	"\rDigestQueries\x12!\n" +
	"\fmerkle_depth\x18\x01 \x01(\rR\vmerkleDepth\x12/\n" +
	"\aqueries\x18\x02 \x03(\v2\x15.peers.v1.DigestQueryR\aqueries\"X\n" +
	"\fDigestUpdate\x12\x12\n" +
	"\x04path\x18\x01 \x03(\rR\x04path\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"d\n" +
	"\rDigestUpdates\x12!\n" +
	"\fmerkle_depth\x18\x01 \x01(\rR\vmerkleDepth\x120\n" +
	"\aupdates\x18\x02 \x03(\v2\x16.peers.v1.DigestUpdateR\aupdates\"\xb1\x03\n" +
	"\x1aEventReconciliationMessage\x12*\n" +
	"\x06events\x18\x01 \x01(\v2\x10.peers.v1.EventsH\x00R\x06events\x127\n" +
	"\vsend_events\x18\x02 \x01(\v2\x14.peers.v1.SendEventsH\x00R\n" +
	"sendEvents\x12c\n" +
	"\x1bsend_events_after_timestamp\x18\x03 \x01(\v2\".peers.v1.SendEventsAfterTimestampH\x00R\x18sendEventsAfterTimestamp\x12:\n" +
	"\fprune_events\x18\x04 \x01(\v2\x15.peers.v1.PruneEventsH\x00R\vpruneEvents\x12@\n" +
	"\x0edigest_queries\x18\x05 \x01(\v2\x17.peers.v1.DigestQueriesH\x00R\rdigestQueries\x12@\n" +
	"\x0edigest_updates\x18\x06 \x01(\v2\x17.peers.v1.DigestUpdatesH\x00R\rdigestUpdatesB\t\n" +
	"\amessageB\x0fZ\rproto/peerspbb\x06proto3"

var (
	file_peers_v1_event_reconciliation_proto_rawDescOnce sync.Once
	file_peers_v1_event_reconciliation_proto_rawDescData []byte
)

func file_peers_v1_event_reconciliation_proto_rawDescGZIP() []byte {
	file_peers_v1_event_reconciliation_proto_rawDescOnce.Do(func() {
		file_peers_v1_event_reconciliation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peers_v1_event_reconciliation_proto_rawDesc), len(file_peers_v1_event_reconciliation_proto_rawDesc)))
	})
	return file_peers_v1_event_reconciliation_proto_rawDescData
}

var file_peers_v1_event_reconciliation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_peers_v1_event_reconciliation_proto_goTypes = []any{
	(*Event)(nil),                      // 0: peers.v1.Event
	(*Events)(nil),                     // 1: peers.v1.Events
	(*SendEvents)(nil),                 // 2: peers.v1.SendEvents
	(*SendEventsAfterTimestamp)(nil),   // 3: peers.v1.SendEventsAfterTimestamp
	(*PruneEvents)(nil),                // 4: peers.v1.PruneEvents
	(*DigestQuery)(nil),                // 5: peers.v1.DigestQuery
	(*DigestQueries)(nil),              // 6: peers.v1.DigestQueries
	(*DigestUpdate)(nil),               // 7: peers.v1.DigestUpdate
	(*DigestUpdates)(nil),              // 8: peers.v1.DigestUpdates
	(*EventReconciliationMessage)(nil), // 9: peers.v1.EventReconciliationMessage
}
var file_peers_v1_event_reconciliation_proto_depIdxs = []int32{
	0, // 0: peers.v1.Events.events:type_name -> peers.v1.Event
	5, // 1: peers.v1.DigestQueries.queries:type_name -> peers.v1.DigestQuery
	7, // 2: peers.v1.DigestUpdates.updates:type_name -> peers.v1.DigestUpdate
	1, // 3: peers.v1.EventReconciliationMessage.events:type_name -> peers.v1.Events
	2, // 4: peers.v1.EventReconciliationMessage.send_events:type_name -> peers.v1.SendEvents
	3, // 5: peers.v1.EventReconciliationMessage.send_events_after_timestamp:type_name -> peers.v1.SendEventsAfterTimestamp
	4, // 6: peers.v1.EventReconciliationMessage.prune_events:type_name -> peers.v1.PruneEvents
	6, // 7: peers.v1.EventReconciliationMessage.digest_queries:type_name -> peers.v1.DigestQueries
	8, // 8: peers.v1.EventReconciliationMessage.digest_updates:type_name -> peers.v1.DigestUpdates
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_peers_v1_event_reconciliation_proto_init() }
func file_peers_v1_event_reconciliation_proto_init() {
	if File_peers_v1_event_reconciliation_proto != nil {
		return
	}
	file_peers_v1_event_reconciliation_proto_msgTypes[9].OneofWrappers = []any{
		(*EventReconciliationMessage_Events)(nil),
		(*EventReconciliationMessage_SendEvents)(nil),
		(*EventReconciliationMessage_SendEventsAfterTimestamp)(nil),
		(*EventReconciliationMessage_PruneEvents)(nil),
		(*EventReconciliationMessage_DigestQueries)(nil),
		(*EventReconciliationMessage_DigestUpdates)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peers_v1_event_reconciliation_proto_rawDesc), len(file_peers_v1_event_reconciliation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peers_v1_event_reconciliation_proto_goTypes,
		DependencyIndexes: file_peers_v1_event_reconciliation_proto_depIdxs,
		MessageInfos:      file_peers_v1_event_reconciliation_proto_msgTypes,
	}.Build()
	File_peers_v1_event_reconciliation_proto = out.File
	file_peers_v1_event_reconciliation_proto_goTypes = nil
	file_peers_v1_event_reconciliation_proto_depIdxs = nil
}
