// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: peers/v1/peer.proto

package peerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Backup              bool                   `protobuf:"varint,1,opt,name=backup,proto3" json:"backup,omitempty"`
	Broadcast           bool                   `protobuf:"varint,2,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	EventReconciliation bool                   `protobuf:"varint,3,opt,name=event_reconciliation,json=eventReconciliation,proto3" json:"event_reconciliation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_peers_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *Capabilities) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

func (x *Capabilities) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *Capabilities) GetEventReconciliation() bool {
	if x != nil {
		return x.EventReconciliation
	}
	return false
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *Capabilities          `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_peers_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type PeerMessagePayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PeerMessagePayload_Handshake
	//	*PeerMessagePayload_BackupMessage
	//	*PeerMessagePayload_BroadcastMessage
	//	*PeerMessagePayload_EventReconciliation
	Payload       isPeerMessagePayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessagePayload) Reset() {
	*x = PeerMessagePayload{}
	mi := &file_peers_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessagePayload) ProtoMessage() {}

func (x *PeerMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessagePayload.ProtoReflect.Descriptor instead.
func (*PeerMessagePayload) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *PeerMessagePayload) GetPayload() isPeerMessagePayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PeerMessagePayload) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*PeerMessagePayload_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *PeerMessagePayload) GetBackupMessage() *BackupMessage {
	if x != nil {
		if x, ok := x.Payload.(*PeerMessagePayload_BackupMessage); ok {
			return x.BackupMessage
		}
	}
	return nil
}

func (x *PeerMessagePayload) GetBroadcastMessage() *BroadcastMessage {
	if x != nil {
		if x, ok := x.Payload.(*PeerMessagePayload_BroadcastMessage); ok {
			return x.BroadcastMessage
		}
	}
	return nil
}

func (x *PeerMessagePayload) GetEventReconciliation() *EventReconciliationMessage {
	if x != nil {
		if x, ok := x.Payload.(*PeerMessagePayload_EventReconciliation); ok {
			return x.EventReconciliation
		}
	}
	return nil
}

type isPeerMessagePayload_Payload interface {
	isPeerMessagePayload_Payload()
}

type PeerMessagePayload_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,3,opt,name=handshake,proto3,oneof"`
}

type PeerMessagePayload_BackupMessage struct {
	BackupMessage *BackupMessage `protobuf:"bytes,4,opt,name=backup_message,json=backupMessage,proto3,oneof"`
}

type PeerMessagePayload_BroadcastMessage struct {
	BroadcastMessage *BroadcastMessage `protobuf:"bytes,5,opt,name=broadcast_message,json=broadcastMessage,proto3,oneof"`
}

type PeerMessagePayload_EventReconciliation struct {
	EventReconciliation *EventReconciliationMessage `protobuf:"bytes,6,opt,name=event_reconciliation,json=eventReconciliation,proto3,oneof"`
}

func (*PeerMessagePayload_Handshake) isPeerMessagePayload_Payload() {}

func (*PeerMessagePayload_BackupMessage) isPeerMessagePayload_Payload() {}

func (*PeerMessagePayload_BroadcastMessage) isPeerMessagePayload_Payload() {}

func (*PeerMessagePayload_EventReconciliation) isPeerMessagePayload_Payload() {}

type PeerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Message       *PeerMessagePayload    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage) Reset() {
	*x = PeerMessage{}
	mi := &file_peers_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage) ProtoMessage() {}

func (x *PeerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peers_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage.ProtoReflect.Descriptor instead.
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return file_peers_v1_peer_proto_rawDescGZIP(), []int{3}
}

func (x *PeerMessage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PeerMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PeerMessage) GetMessage() *PeerMessagePayload {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_peers_v1_peer_proto protoreflect.FileDescriptor

const file_peers_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x13peers/v1/peer.proto\x12\bpeers.v1\x1a\x15peers/v1/backup.proto\x1a\x18peers/v1/broadcast.proto\x1a#peers/v1/event_reconciliation.proto\"w\n" +
	"\fCapabilities\x12\x16\n" +
	"\x06backup\x18\x01 \x01(\bR\x06backup\x12\x1c\n" +
	"\tbroadcast\x18\x02 \x01(\bR\tbroadcast\x121\n" +
	"\x14event_reconciliation\x18\x03 \x01(\bR\x13eventReconciliation\"G\n" +
	"\tHandshake\x12:\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x16.peers.v1.CapabilitiesR\fcapabilities\"\xbc\x02\n" +
	"\x12PeerMessagePayload\x123\n" +
	"\thandshake\x18\x03 \x01(\v2\x13.peers.v1.HandshakeH\x00R\thandshake\x12@\n" +
	"\x0ebackup_message\x18\x04 \x01(\v2\x17.peers.v1.BackupMessageH\x00R\rbackupMessage\x12I\n" +
	"\x11broadcast_message\x18\x05 \x01(\v2\x1a.peers.v1.BroadcastMessageH\x00R\x10broadcastMessage\x12Y\n" +
	"\x14event_reconciliation\x18\x06 \x01(\v2$.peers.v1.EventReconciliationMessageH\x00R\x13eventReconciliationB\t\n" +
	"\apayload\"\x81\x01\n" +
	"\vPeerMessage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x126\n" +
	"\amessage\x18\x03 \x01(\v2\x1c.peers.v1.PeerMessagePayloadR\amessageB\x0fZ\rproto/peerspbb\x06proto3"

var (
	file_peers_v1_peer_proto_rawDescOnce sync.Once
	file_peers_v1_peer_proto_rawDescData []byte
)

func file_peers_v1_peer_proto_rawDescGZIP() []byte {
	file_peers_v1_peer_proto_rawDescOnce.Do(func() {
		file_peers_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peers_v1_peer_proto_rawDesc), len(file_peers_v1_peer_proto_rawDesc)))
	})
	return file_peers_v1_peer_proto_rawDescData
}

var file_peers_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_peers_v1_peer_proto_goTypes = []any{
	(*Capabilities)(nil),               // 0: peers.v1.Capabilities
	(*Handshake)(nil),                  // 1: peers.v1.Handshake
	(*PeerMessagePayload)(nil),         // 2: peers.v1.PeerMessagePayload
	(*PeerMessage)(nil),                // 3: peers.v1.PeerMessage
	(*BackupMessage)(nil),              // 4: peers.v1.BackupMessage
	(*BroadcastMessage)(nil),           // 5: peers.v1.BroadcastMessage
	(*EventReconciliationMessage)(nil), // 6: peers.v1.EventReconciliationMessage
}
var file_peers_v1_peer_proto_depIdxs = []int32{
	0, // 0: peers.v1.Handshake.capabilities:type_name -> peers.v1.Capabilities
	1, // 1: peers.v1.PeerMessagePayload.handshake:type_name -> peers.v1.Handshake
	4, // 2: peers.v1.PeerMessagePayload.backup_message:type_name -> peers.v1.BackupMessage
	5, // 3: peers.v1.PeerMessagePayload.broadcast_message:type_name -> peers.v1.BroadcastMessage
	6, // 4: peers.v1.PeerMessagePayload.event_reconciliation:type_name -> peers.v1.EventReconciliationMessage
	2, // 5: peers.v1.PeerMessage.message:type_name -> peers.v1.PeerMessagePayload
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_peers_v1_peer_proto_init() }
func file_peers_v1_peer_proto_init() {
	if File_peers_v1_peer_proto != nil {
		return
	}
	file_peers_v1_backup_proto_init()
	file_peers_v1_broadcast_proto_init()
	file_peers_v1_event_reconciliation_proto_init()
	file_peers_v1_peer_proto_msgTypes[2].OneofWrappers = []any{
		(*PeerMessagePayload_Handshake)(nil),
		(*PeerMessagePayload_BackupMessage)(nil),
		(*PeerMessagePayload_BroadcastMessage)(nil),
		(*PeerMessagePayload_EventReconciliation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peers_v1_peer_proto_rawDesc), len(file_peers_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peers_v1_peer_proto_goTypes,
		DependencyIndexes: file_peers_v1_peer_proto_depIdxs,
		MessageInfos:      file_peers_v1_peer_proto_msgTypes,
	}.Build()
	File_peers_v1_peer_proto = out.File
	file_peers_v1_peer_proto_goTypes = nil
	file_peers_v1_peer_proto_depIdxs = nil
}
