// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/event.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Data          *EventData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Event) GetData() *EventData {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to EventType:
	//
	//	*EventData_CreateProvider
	//	*EventData_UpdateProvider
	//	*EventData_CreateMcp
	//	*EventData_UpdateMcp
	//	*EventData_CreateChat
	//	*EventData_UpdateChat
	//	*EventData_DeleteProvider
	//	*EventData_DeleteMcp
	//	*EventData_DeleteChat
	//	*EventData_SetUserMetadata
	//	*EventData_CreatePreset
	//	*EventData_UpdatePreset
	//	*EventData_DeletePreset
	//	*EventData_IncrementChatAccessCount
	//	*EventData_DeleteUserMetadata
	EventType     isEventData_EventType `protobuf_oneof:"event_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_events_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventData) GetEventType() isEventData_EventType {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *EventData) GetCreateProvider() *CreateProviderEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_CreateProvider); ok {
			return x.CreateProvider
		}
	}
	return nil
}

func (x *EventData) GetUpdateProvider() *UpdateProviderEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_UpdateProvider); ok {
			return x.UpdateProvider
		}
	}
	return nil
}

func (x *EventData) GetCreateMcp() *CreateMCPEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_CreateMcp); ok {
			return x.CreateMcp
		}
	}
	return nil
}

func (x *EventData) GetUpdateMcp() *UpdateMCPEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_UpdateMcp); ok {
			return x.UpdateMcp
		}
	}
	return nil
}

func (x *EventData) GetCreateChat() *CreateChatEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_CreateChat); ok {
			return x.CreateChat
		}
	}
	return nil
}

func (x *EventData) GetUpdateChat() *UpdateChatEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_UpdateChat); ok {
			return x.UpdateChat
		}
	}
	return nil
}

func (x *EventData) GetDeleteProvider() *DeleteProviderEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_DeleteProvider); ok {
			return x.DeleteProvider
		}
	}
	return nil
}

func (x *EventData) GetDeleteMcp() *DeleteMCPEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_DeleteMcp); ok {
			return x.DeleteMcp
		}
	}
	return nil
}

func (x *EventData) GetDeleteChat() *DeleteChatEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_DeleteChat); ok {
			return x.DeleteChat
		}
	}
	return nil
}

func (x *EventData) GetSetUserMetadata() *SetUserMetadataEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_SetUserMetadata); ok {
			return x.SetUserMetadata
		}
	}
	return nil
}

func (x *EventData) GetCreatePreset() *CreatePresetEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_CreatePreset); ok {
			return x.CreatePreset
		}
	}
	return nil
}

func (x *EventData) GetUpdatePreset() *UpdatePresetEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_UpdatePreset); ok {
			return x.UpdatePreset
		}
	}
	return nil
}

func (x *EventData) GetDeletePreset() *DeletePresetEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_DeletePreset); ok {
			return x.DeletePreset
		}
	}
	return nil
}

func (x *EventData) GetIncrementChatAccessCount() *IncrementChatAccessCountEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_IncrementChatAccessCount); ok {
			return x.IncrementChatAccessCount
		}
	}
	return nil
}

func (x *EventData) GetDeleteUserMetadata() *DeleteUserMetadataEvent {
	if x != nil {
		if x, ok := x.EventType.(*EventData_DeleteUserMetadata); ok {
			return x.DeleteUserMetadata
		}
	}
	return nil
}

type isEventData_EventType interface {
	isEventData_EventType()
}

type EventData_CreateProvider struct {
	CreateProvider *CreateProviderEvent `protobuf:"bytes,1,opt,name=create_provider,json=createProvider,proto3,oneof"`
}

type EventData_UpdateProvider struct {
	UpdateProvider *UpdateProviderEvent `protobuf:"bytes,2,opt,name=update_provider,json=updateProvider,proto3,oneof"`
}

type EventData_CreateMcp struct {
	CreateMcp *CreateMCPEvent `protobuf:"bytes,3,opt,name=create_mcp,json=createMcp,proto3,oneof"`
}

type EventData_UpdateMcp struct {
	UpdateMcp *UpdateMCPEvent `protobuf:"bytes,4,opt,name=update_mcp,json=updateMcp,proto3,oneof"`
}

type EventData_CreateChat struct {
	CreateChat *CreateChatEvent `protobuf:"bytes,5,opt,name=create_chat,json=createChat,proto3,oneof"`
}

type EventData_UpdateChat struct {
	UpdateChat *UpdateChatEvent `protobuf:"bytes,6,opt,name=update_chat,json=updateChat,proto3,oneof"`
}

type EventData_DeleteProvider struct {
	DeleteProvider *DeleteProviderEvent `protobuf:"bytes,7,opt,name=delete_provider,json=deleteProvider,proto3,oneof"`
}

type EventData_DeleteMcp struct {
	DeleteMcp *DeleteMCPEvent `protobuf:"bytes,8,opt,name=delete_mcp,json=deleteMcp,proto3,oneof"`
}

type EventData_DeleteChat struct {
	DeleteChat *DeleteChatEvent `protobuf:"bytes,9,opt,name=delete_chat,json=deleteChat,proto3,oneof"`
}

type EventData_SetUserMetadata struct {
	SetUserMetadata *SetUserMetadataEvent `protobuf:"bytes,10,opt,name=set_user_metadata,json=setUserMetadata,proto3,oneof"`
}

type EventData_CreatePreset struct {
	CreatePreset *CreatePresetEvent `protobuf:"bytes,11,opt,name=create_preset,json=createPreset,proto3,oneof"`
}

type EventData_UpdatePreset struct {
	UpdatePreset *UpdatePresetEvent `protobuf:"bytes,12,opt,name=update_preset,json=updatePreset,proto3,oneof"`
}

type EventData_DeletePreset struct {
	DeletePreset *DeletePresetEvent `protobuf:"bytes,13,opt,name=delete_preset,json=deletePreset,proto3,oneof"`
}

type EventData_IncrementChatAccessCount struct {
	IncrementChatAccessCount *IncrementChatAccessCountEvent `protobuf:"bytes,14,opt,name=increment_chat_access_count,json=incrementChatAccessCount,proto3,oneof"`
}

type EventData_DeleteUserMetadata struct {
	DeleteUserMetadata *DeleteUserMetadataEvent `protobuf:"bytes,15,opt,name=delete_user_metadata,json=deleteUserMetadata,proto3,oneof"`
}

func (*EventData_CreateProvider) isEventData_EventType() {}

func (*EventData_UpdateProvider) isEventData_EventType() {}

func (*EventData_CreateMcp) isEventData_EventType() {}

func (*EventData_UpdateMcp) isEventData_EventType() {}

func (*EventData_CreateChat) isEventData_EventType() {}

func (*EventData_UpdateChat) isEventData_EventType() {}

func (*EventData_DeleteProvider) isEventData_EventType() {}

func (*EventData_DeleteMcp) isEventData_EventType() {}

func (*EventData_DeleteChat) isEventData_EventType() {}

func (*EventData_SetUserMetadata) isEventData_EventType() {}

func (*EventData_CreatePreset) isEventData_EventType() {}

func (*EventData_UpdatePreset) isEventData_EventType() {}

func (*EventData_DeletePreset) isEventData_EventType() {}

func (*EventData_IncrementChatAccessCount) isEventData_EventType() {}

func (*EventData_DeleteUserMetadata) isEventData_EventType() {}

type IncrementChatAccessCountEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementChatAccessCountEvent) Reset() {
	*x = IncrementChatAccessCountEvent{}
	mi := &file_events_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementChatAccessCountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementChatAccessCountEvent) ProtoMessage() {}

func (x *IncrementChatAccessCountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementChatAccessCountEvent.ProtoReflect.Descriptor instead.
func (*IncrementChatAccessCountEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *IncrementChatAccessCountEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateProviderEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseUrl         string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Token           string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	DefaultModelIds []string               `protobuf:"bytes,6,rep,name=default_model_ids,json=defaultModelIds,proto3" json:"default_model_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProviderEvent) Reset() {
	*x = CreateProviderEvent{}
	mi := &file_events_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderEvent) ProtoMessage() {}

func (x *CreateProviderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderEvent.ProtoReflect.Descriptor instead.
func (*CreateProviderEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProviderEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateProviderEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProviderEvent) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateProviderEvent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateProviderEvent) GetDefaultModelIds() []string {
	if x != nil {
		return x.DefaultModelIds
	}
	return nil
}

type UpdateProviderEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Type            *string                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	BaseUrl         *string                `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3,oneof" json:"base_url,omitempty"`
	Token           *string                `protobuf:"bytes,5,opt,name=token,proto3,oneof" json:"token,omitempty"`
	DefaultModelIds []string               `protobuf:"bytes,6,rep,name=default_model_ids,json=defaultModelIds,proto3" json:"default_model_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProviderEvent) Reset() {
	*x = UpdateProviderEvent{}
	mi := &file_events_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderEvent) ProtoMessage() {}

func (x *UpdateProviderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderEvent.ProtoReflect.Descriptor instead.
func (*UpdateProviderEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProviderEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProviderEvent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProviderEvent) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateProviderEvent) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *UpdateProviderEvent) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *UpdateProviderEvent) GetDefaultModelIds() []string {
	if x != nil {
		return x.DefaultModelIds
	}
	return nil
}

type CreateMCPEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMCPEvent) Reset() {
	*x = CreateMCPEvent{}
	mi := &file_events_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMCPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMCPEvent) ProtoMessage() {}

func (x *CreateMCPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMCPEvent.ProtoReflect.Descriptor instead.
func (*CreateMCPEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMCPEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateMCPEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMCPEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateMCPEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMCPEvent) Reset() {
	*x = UpdateMCPEvent{}
	mi := &file_events_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMCPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMCPEvent) ProtoMessage() {}

func (x *UpdateMCPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMCPEvent.ProtoReflect.Descriptor instead.
func (*UpdateMCPEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMCPEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMCPEvent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateMCPEvent) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type CreateChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Finished      bool                   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	Messages      *structpb.Struct       `protobuf:"bytes,5,opt,name=messages,proto3" json:"messages,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatEvent) Reset() {
	*x = CreateChatEvent{}
	mi := &file_events_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatEvent) ProtoMessage() {}

func (x *CreateChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatEvent.ProtoReflect.Descriptor instead.
func (*CreateChatEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *CreateChatEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateChatEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChatEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateChatEvent) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *CreateChatEvent) GetMessages() *structpb.Struct {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CreateChatEvent) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Finished      *bool                  `protobuf:"varint,4,opt,name=finished,proto3,oneof" json:"finished,omitempty"`
	Messages      *structpb.Struct       `protobuf:"bytes,5,opt,name=messages,proto3,oneof" json:"messages,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,6,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatEvent) Reset() {
	*x = UpdateChatEvent{}
	mi := &file_events_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatEvent) ProtoMessage() {}

func (x *UpdateChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatEvent.ProtoReflect.Descriptor instead.
func (*UpdateChatEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateChatEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChatEvent) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateChatEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateChatEvent) GetFinished() bool {
	if x != nil && x.Finished != nil {
		return *x.Finished
	}
	return false
}

func (x *UpdateChatEvent) GetMessages() *structpb.Struct {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *UpdateChatEvent) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreatePresetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePresetEvent) Reset() {
	*x = CreatePresetEvent{}
	mi := &file_events_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePresetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePresetEvent) ProtoMessage() {}

func (x *CreatePresetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePresetEvent.ProtoReflect.Descriptor instead.
func (*CreatePresetEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePresetEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePresetEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePresetEvent) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdatePresetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Settings      *structpb.Struct       `protobuf:"bytes,3,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresetEvent) Reset() {
	*x = UpdatePresetEvent{}
	mi := &file_events_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresetEvent) ProtoMessage() {}

func (x *UpdatePresetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresetEvent.ProtoReflect.Descriptor instead.
func (*UpdatePresetEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePresetEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePresetEvent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePresetEvent) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type DeletePresetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePresetEvent) Reset() {
	*x = DeletePresetEvent{}
	mi := &file_events_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePresetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePresetEvent) ProtoMessage() {}

func (x *DeletePresetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePresetEvent.ProtoReflect.Descriptor instead.
func (*DeletePresetEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePresetEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProviderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderEvent) Reset() {
	*x = DeleteProviderEvent{}
	mi := &file_events_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderEvent) ProtoMessage() {}

func (x *DeleteProviderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderEvent.ProtoReflect.Descriptor instead.
func (*DeleteProviderEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProviderEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMCPEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMCPEvent) Reset() {
	*x = DeleteMCPEvent{}
	mi := &file_events_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMCPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMCPEvent) ProtoMessage() {}

func (x *DeleteMCPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMCPEvent.ProtoReflect.Descriptor instead.
func (*DeleteMCPEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMCPEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatEvent) Reset() {
	*x = DeleteChatEvent{}
	mi := &file_events_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatEvent) ProtoMessage() {}

func (x *DeleteChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatEvent.ProtoReflect.Descriptor instead.
func (*DeleteChatEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteChatEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetUserMetadataEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserMetadataEvent) Reset() {
	*x = SetUserMetadataEvent{}
	mi := &file_events_v1_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserMetadataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserMetadataEvent) ProtoMessage() {}

func (x *SetUserMetadataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserMetadataEvent.ProtoReflect.Descriptor instead.
func (*SetUserMetadataEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{15}
}

func (x *SetUserMetadataEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetUserMetadataEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteUserMetadataEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserMetadataEvent) Reset() {
	*x = DeleteUserMetadataEvent{}
	mi := &file_events_v1_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserMetadataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserMetadataEvent) ProtoMessage() {}

func (x *DeleteUserMetadataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserMetadataEvent.ProtoReflect.Descriptor instead.
func (*DeleteUserMetadataEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserMetadataEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SyncServerGetEventsResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncServerGetEventsResponsePayload) Reset() {
	*x = SyncServerGetEventsResponsePayload{}
	mi := &file_events_v1_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncServerGetEventsResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncServerGetEventsResponsePayload) ProtoMessage() {}

func (x *SyncServerGetEventsResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncServerGetEventsResponsePayload.ProtoReflect.Descriptor instead.
func (*SyncServerGetEventsResponsePayload) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{17}
}

func (x *SyncServerGetEventsResponsePayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SyncServerGetEventsResponsePayload) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SyncServerGetEventsResponsePayload) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type SyncServerGetEventsResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	HasMore       bool                                  `protobuf:"varint,1,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextAfter     *string                               `protobuf:"bytes,2,opt,name=next_after,json=nextAfter,proto3,oneof" json:"next_after,omitempty"`
	PageSize      uint32                                `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Events        []*SyncServerGetEventsResponsePayload `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncServerGetEventsResponse) Reset() {
	*x = SyncServerGetEventsResponse{}
	mi := &file_events_v1_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncServerGetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncServerGetEventsResponse) ProtoMessage() {}

func (x *SyncServerGetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncServerGetEventsResponse.ProtoReflect.Descriptor instead.
func (*SyncServerGetEventsResponse) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{18}
}

func (x *SyncServerGetEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SyncServerGetEventsResponse) GetNextAfter() string {
	if x != nil && x.NextAfter != nil {
		return *x.NextAfter
	}
	return ""
}

func (x *SyncServerGetEventsResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SyncServerGetEventsResponse) GetEvents() []*SyncServerGetEventsResponsePayload {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_events_v1_event_proto protoreflect.FileDescriptor

const file_events_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/event.proto\x12\tevents.v1\x1a\x1cgoogle/protobuf/struct.proto\"K\n" +
	"\x05Event\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.events.v1.EventDataR\x04data\"\xcc\b\n" +
	"\tEventData\x12I\n" +
	"\x0fcreate_provider\x18\x01 \x01(\v2\x1e.events.v1.CreateProviderEventH\x00R\x0ecreateProvider\x12I\n" +
	"\x0fupdate_provider\x18\x02 \x01(\v2\x1e.events.v1.UpdateProviderEventH\x00R\x0eupdateProvider\x12:\n" +
	"\n" +
	"create_mcp\x18\x03 \x01(\v2\x19.events.v1.CreateMCPEventH\x00R\tcreateMcp\x12:\n" +
	"\n" +
	"update_mcp\x18\x04 \x01(\v2\x19.events.v1.UpdateMCPEventH\x00R\tupdateMcp\x12=\n" +
	"\vcreate_chat\x18\x05 \x01(\v2\x1a.events.v1.CreateChatEventH\x00R\n" +
	"createChat\x12=\n" +
	"\vupdate_chat\x18\x06 \x01(\v2\x1a.events.v1.UpdateChatEventH\x00R\n" +
	"updateChat\x12I\n" +
	"\x0fdelete_provider\x18\a \x01(\v2\x1e.events.v1.DeleteProviderEventH\x00R\x0edeleteProvider\x12:\n" +
	"\n" +
	"delete_mcp\x18\b \x01(\v2\x19.events.v1.DeleteMCPEventH\x00R\tdeleteMcp\x12=\n" +
	"\vdelete_chat\x18\t \x01(\v2\x1a.events.v1.DeleteChatEventH\x00R\n" +
	"deleteChat\x12M\n" +
	"\x11set_user_metadata\x18\n" +
	" \x01(\v2\x1f.events.v1.SetUserMetadataEventH\x00R\x0fsetUserMetadata\x12C\n" +
	"\rcreate_preset\x18\v \x01(\v2\x1c.events.v1.CreatePresetEventH\x00R\fcreatePreset\x12C\n" +
	"\rupdate_preset\x18\f \x01(\v2\x1c.events.v1.UpdatePresetEventH\x00R\fupdatePreset\x12C\n" +
	"\rdelete_preset\x18\r \x01(\v2\x1c.events.v1.DeletePresetEventH\x00R\fdeletePreset\x12i\n" +
	"\x1bincrement_chat_access_count\x18\x0e \x01(\v2(.events.v1.IncrementChatAccessCountEventH\x00R\x18incrementChatAccessCount\x12V\n" +
	"\x14delete_user_metadata\x18\x0f \x01(\v2\".events.v1.DeleteUserMetadataEventH\x00R\x12deleteUserMetadataB\f\n" +
	"\n" +
	"event_type\"/\n" +
	"\x1dIncrementChatAccessCountEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x13CreateProviderEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12*\n" +
	"\x11default_model_ids\x18\x06 \x03(\tR\x0fdefaultModelIds\"\xe7\x01\n" +
	"\x13UpdateProviderEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x01R\x04type\x88\x01\x01\x12\x1e\n" +
	"\bbase_url\x18\x04 \x01(\tH\x02R\abaseUrl\x88\x01\x01\x12\x19\n" +
	"\x05token\x18\x05 \x01(\tH\x03R\x05token\x88\x01\x01\x12*\n" +
	"\x11default_model_ids\x18\x06 \x03(\tR\x0fdefaultModelIdsB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_typeB\v\n" +
	"\t_base_urlB\b\n" +
	"\x06_token\"F\n" +
	"\x0eCreateMCPEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"a\n" +
	"\x0eUpdateMCPEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x03 \x01(\tH\x01R\x03url\x88\x01\x01B\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_url\"\xd1\x01\n" +
	"\x0fCreateChatEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1a\n" +
	"\bfinished\x18\x04 \x01(\bR\bfinished\x123\n" +
	"\bmessages\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmessages\x123\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bsettings\"\x96\x02\n" +
	"\x0fUpdateChatEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1f\n" +
	"\bfinished\x18\x04 \x01(\bH\x01R\bfinished\x88\x01\x01\x128\n" +
	"\bmessages\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x02R\bmessages\x88\x01\x01\x128\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x03R\bsettings\x88\x01\x01B\b\n" +
	"\x06_titleB\v\n" +
	"\t_finishedB\v\n" +
	"\t_messagesB\v\n" +
	"\t_settings\"l\n" +
	"\x11CreatePresetEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\bsettings\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bsettings\"\x8c\x01\n" +
	"\x11UpdatePresetEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x128\n" +
	"\bsettings\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\bsettings\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_settings\"#\n" +
	"\x11DeletePresetEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeleteProviderEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eDeleteMCPEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fDeleteChatEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x14SetUserMetadataEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\")\n" +
	"\x17DeleteUserMetadataEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"t\n" +
	"\"SyncServerGetEventsResponsePayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"\xcf\x01\n" +
	"\x1bSyncServerGetEventsResponse\x12\x19\n" +
	"\bhas_more\x18\x01 \x01(\bR\ahasMore\x12\"\n" +
	"\n" +
	"next_after\x18\x02 \x01(\tH\x00R\tnextAfter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12E\n" +
	"\x06events\x18\x04 \x03(\v2-.events.v1.SyncServerGetEventsResponsePayloadR\x06eventsB\r\n" +
	"\v_next_afterB\x13Z\x11proto/rllm/eventsb\x06proto3"

var (
	file_events_v1_event_proto_rawDescOnce sync.Once
	file_events_v1_event_proto_rawDescData []byte
)

func file_events_v1_event_proto_rawDescGZIP() []byte {
	file_events_v1_event_proto_rawDescOnce.Do(func() {
		file_events_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_event_proto_rawDesc), len(file_events_v1_event_proto_rawDesc)))
	})
	return file_events_v1_event_proto_rawDescData
}

var file_events_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_events_v1_event_proto_goTypes = []any{
	(*Event)(nil),                              // 0: events.v1.Event
	(*EventData)(nil),                          // 1: events.v1.EventData
	(*IncrementChatAccessCountEvent)(nil),      // 2: events.v1.IncrementChatAccessCountEvent
	(*CreateProviderEvent)(nil),                // 3: events.v1.CreateProviderEvent
	(*UpdateProviderEvent)(nil),                // 4: events.v1.UpdateProviderEvent
	(*CreateMCPEvent)(nil),                     // 5: events.v1.CreateMCPEvent
	(*UpdateMCPEvent)(nil),                     // 6: events.v1.UpdateMCPEvent
	(*CreateChatEvent)(nil),                    // 7: events.v1.CreateChatEvent
	(*UpdateChatEvent)(nil),                    // 8: events.v1.UpdateChatEvent
	(*CreatePresetEvent)(nil),                  // 9: events.v1.CreatePresetEvent
	(*UpdatePresetEvent)(nil),                  // 10: events.v1.UpdatePresetEvent
	(*DeletePresetEvent)(nil),                  // 11: events.v1.DeletePresetEvent
	(*DeleteProviderEvent)(nil),                // 12: events.v1.DeleteProviderEvent
	(*DeleteMCPEvent)(nil),                     // 13: events.v1.DeleteMCPEvent
	(*DeleteChatEvent)(nil),                    // 14: events.v1.DeleteChatEvent
	(*SetUserMetadataEvent)(nil),               // 15: events.v1.SetUserMetadataEvent
	(*DeleteUserMetadataEvent)(nil),            // 16: events.v1.DeleteUserMetadataEvent
	(*SyncServerGetEventsResponsePayload)(nil), // 17: events.v1.SyncServerGetEventsResponsePayload
	(*SyncServerGetEventsResponse)(nil),        // 18: events.v1.SyncServerGetEventsResponse
	(*structpb.Struct)(nil),                    // 19: google.protobuf.Struct
}
var file_events_v1_event_proto_depIdxs = []int32{
	1,  // 0: events.v1.Event.data:type_name -> events.v1.EventData
	3,  // 1: events.v1.EventData.create_provider:type_name -> events.v1.CreateProviderEvent
	4,  // 2: events.v1.EventData.update_provider:type_name -> events.v1.UpdateProviderEvent
	5,  // 3: events.v1.EventData.create_mcp:type_name -> events.v1.CreateMCPEvent
	6,  // 4: events.v1.EventData.update_mcp:type_name -> events.v1.UpdateMCPEvent
	7,  // 5: events.v1.EventData.create_chat:type_name -> events.v1.CreateChatEvent
	8,  // 6: events.v1.EventData.update_chat:type_name -> events.v1.UpdateChatEvent
	12, // 7: events.v1.EventData.delete_provider:type_name -> events.v1.DeleteProviderEvent
	13, // 8: events.v1.EventData.delete_mcp:type_name -> events.v1.DeleteMCPEvent
	14, // 9: events.v1.EventData.delete_chat:type_name -> events.v1.DeleteChatEvent
	15, // 10: events.v1.EventData.set_user_metadata:type_name -> events.v1.SetUserMetadataEvent
	9,  // 11: events.v1.EventData.create_preset:type_name -> events.v1.CreatePresetEvent
	10, // 12: events.v1.EventData.update_preset:type_name -> events.v1.UpdatePresetEvent
	11, // 13: events.v1.EventData.delete_preset:type_name -> events.v1.DeletePresetEvent
	2,  // 14: events.v1.EventData.increment_chat_access_count:type_name -> events.v1.IncrementChatAccessCountEvent
	16, // 15: events.v1.EventData.delete_user_metadata:type_name -> events.v1.DeleteUserMetadataEvent
	19, // 16: events.v1.CreateChatEvent.messages:type_name -> google.protobuf.Struct
	19, // 17: events.v1.CreateChatEvent.settings:type_name -> google.protobuf.Struct
	19, // 18: events.v1.UpdateChatEvent.messages:type_name -> google.protobuf.Struct
	19, // 19: events.v1.UpdateChatEvent.settings:type_name -> google.protobuf.Struct
	19, // 20: events.v1.CreatePresetEvent.settings:type_name -> google.protobuf.Struct
	19, // 21: events.v1.UpdatePresetEvent.settings:type_name -> google.protobuf.Struct
	17, // 22: events.v1.SyncServerGetEventsResponse.events:type_name -> events.v1.SyncServerGetEventsResponsePayload
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_events_v1_event_proto_init() }
func file_events_v1_event_proto_init() {
	if File_events_v1_event_proto != nil {
		return
	}
	file_events_v1_event_proto_msgTypes[1].OneofWrappers = []any{
		(*EventData_CreateProvider)(nil),
		(*EventData_UpdateProvider)(nil),
		(*EventData_CreateMcp)(nil),
		(*EventData_UpdateMcp)(nil),
		(*EventData_CreateChat)(nil),
		(*EventData_UpdateChat)(nil),
		(*EventData_DeleteProvider)(nil),
		(*EventData_DeleteMcp)(nil),
		(*EventData_DeleteChat)(nil),
		(*EventData_SetUserMetadata)(nil),
		(*EventData_CreatePreset)(nil),
		(*EventData_UpdatePreset)(nil),
		(*EventData_DeletePreset)(nil),
		(*EventData_IncrementChatAccessCount)(nil),
		(*EventData_DeleteUserMetadata)(nil),
	}
	file_events_v1_event_proto_msgTypes[4].OneofWrappers = []any{}
	file_events_v1_event_proto_msgTypes[6].OneofWrappers = []any{}
	file_events_v1_event_proto_msgTypes[8].OneofWrappers = []any{}
	file_events_v1_event_proto_msgTypes[10].OneofWrappers = []any{}
	file_events_v1_event_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_event_proto_rawDesc), len(file_events_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_event_proto_goTypes,
		DependencyIndexes: file_events_v1_event_proto_depIdxs,
		MessageInfos:      file_events_v1_event_proto_msgTypes,
	}.Build()
	File_events_v1_event_proto = out.File
	file_events_v1_event_proto_goTypes = nil
	file_events_v1_event_proto_depIdxs = nil
}
